USE RECEPCAO
GO


EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','CODIGO','Codigo de indentificação'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','CODPAC','Codigo do paciente do agendamento'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','NOME','Nome do paciente do agendamento'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','CODMED','Codigo do medico do agendamento'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','CODESP','Codigo da especialidade do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','DTHORA','Data e hora do agendamento'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','TEL','Telefone do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','DTNASC','Data de nascimento do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','CODCONV','Codigo do convenio do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','RUA','Informa a rua do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','BAIRRO','Informa o bairro do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','CIDADE','Informa a cidade do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','CEP','Informa o CEP do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','DOC','Documento do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','DIA','Dia da consulta'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','OPERADOR','Operador que realizou o agendamento'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','DTMARCA','Data do agendamento'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','STAMP','Stamp do registro'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','NUMERO','Numero do registro'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','EXISTECADPRINCIPAL','Informa se o registro contem cadastro principal'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','ENXAIXE','Informa se o agendamento é um encaixe'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','DATAATENDE','Grava data do agendamento'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','OBS','Observação do agendamento'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','TIPOAGENDA','Tipo de agendamento'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','IBGE','Codigo ibge do agendamento'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','NOMEMUN','Nome do municipio do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','CODIGOSUS','Codigo do SUS do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','GRUPOSUS','Codigo da unidade de origem'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','POSTO','Campo andar da ficha na recepcao.dbo.movimentos'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','PESO','Peso do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','SEXO','Sexo do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','IDADE','Idade do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','EXAME','Informa o exame do agendamento em caso de SADT'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','RESPONSAVEL','Informa o nome do responsavel pelo paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','JEJUM','Informa se o paciente precisará estar em jejum'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','CIRURGIA','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','SEDACAO','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','CONTRASTE','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','OBSEXAME','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','EXAMESN','Ex'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','MED','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','CONVEXT','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','CODPROC','Codigo de indentificação do procedimento'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','ULTIMO_OP','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','DDDCEL','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','CELULAR','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','DDD','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','RETORNO','Exibe se o ´paciente terá retorno'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','SEQSADT','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','SETOR','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','PRIMEIRAVEZSN','Primeira vez S para sim N para nao'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','FICHA','Ficha do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','ID_CONEXA','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','AGE_CONSULTA_NOME','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','APELIDO','Apelido do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','ID_AGE_CONSULTA','ID do agendamento da consulta'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','ID_AGE_CONSULTA_HOR','ID do agendamento da consulta hora'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','ID_MOTIVO','ID do motivo do agendamento'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','ID_PROTOCOLO','ID do proptocoloa'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','TIPO_CONEXA','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','TIPO_CONSULTA','Tipo de consulta'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','AGCALLCENTER','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','C_CADGENDHR','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','C_CODAGEND','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','C_CODPROTOCOLO','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','C_CODUNID','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','C_CNESID','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','C_CODPAC','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','NOMEAGEND','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','EXPORTADO','Informa se é o registro é exportado'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','NOMEUSUARIO','Nome do usuario que realizou o agendamento'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','DT_INSERT','Data que fez o insert no banco'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','ID_CODPAC','ID do paciente'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','UNIQUEID','UniqueID do registro'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','ATENDIDO','Codigo de indentificação do sistema'
EXEC RECEPCAO.DBO.SP_SET_COLUMN_DESCRIPTION 'dbo', 'AGENDA','ID_TIPO_ATENDIMENTO','Codigo de indentificação do tipo de atendimento'




