SELECT UPPER(TABLE_CATALOG) AS [DATABASE],
UPPER(TABLE_SCHEMA) AS [SCHEMA],
UPPER(TABLE_NAME) AS TABLE_NAME,
UPPER(COLUMN_NAME) AS COLUMN_NAME,
UPPER(DATA_TYPE) AS DATA_TYPE,
CHARACTER_MAXIMUM_LENGTH,
UPPER(COLUMN_DEFAULT) AS COLUMN_DEFAULT,
CASE IS_NULLABLE
WHEN 'YES' THEN 'TRUE'
ELSE 'FALSE'
END AS NULO,
'ALTER TABLE ' +UPPER(TABLE_CATALOG) + '.'+UPPER(TABLE_SCHEMA)+'.'+ UPPER(TABLE_NAME) + ' ADD ' + UPPER(COLUMN_NAME) + ' ' + UPPER(DATA_TYPE) + CASE
WHEN CONVERT(VARCHAR(50),CHARACTER_MAXIMUM_LENGTH) IS NULL THEN ''
ELSE '(' + CONVERT(VARCHAR(50),CHARACTER_MAXIMUM_LENGTH) + ')'
END + CASE
WHEN COLUMN_DEFAULT IS NULL THEN ''
ELSE ' DEFAULT ' + UPPER(COLUMN_DEFAULT) + ' '
END + CASE IS_NULLABLE
WHEN 'YES' THEN ''
ELSE ' NOT NULL '
END AS COMANDO
FROM RECEPCAO.INFORMATION_SCHEMA.COLUMNS
WHERE COLUMN_NAME LIKE '%TIPO%'
