USE RECEPCAO;
SELECT *
FROM
(
    SELECT DISTINCT
           VW.NOMEEQUIPE [EQUIPE],
           CONVERT(VARCHAR(10), PM.dtatende, 103) [DATA_DE_ATENDIMENTO],
		 COUNT(PM.codpac) [TOTAL_DE_ATENDIMENTOS]
    FROM PACIENTES P
         INNER JOIN Indicadores.vw_pep_siab VW ON P.codigo = VW.IDPep
         INNER JOIN PepMovimentos PM ON PM.codpac = VW.IDPep
	    WHERE PM.Status = 'F' AND PM.DataFinaliza IS NOT NULL
	    GROUP BY VW.NOMEEQUIPE ,CONVERT(VARCHAR(10), PM.dtatende, 103) 
) AT
ORDER BY DATA_DE_ATENDIMENTO OFFSET  100 ROWS FETCH NEXT 200 ROWS ONLY





