USE RECEPCAO

GO

/* SELECT INTO, FUNCIONA PARA CRIARMOS UMA OUTRA TABELA COM OS DADOS DA ORIGINAL, OU ATÉ CRIAR UM BACKUPO DA TABELA
ORIGINAL
A SINTAXE É SELECT CAMPOS QUE DESEJA DA TABELA ORIGINAL, INTO NOME DA NOVA TABELA E FROM O NOME DA TABELA DO SELECT*/

SELECT DISTINCT A.NOME, FORMAT(B.DTATENDE,'d') [DT_ATENDE] INTO DBO.NV_TABLE  FROM PACIENTES A
INNER JOIN PepMovimentos B ON (A.codigo = B.codpac)
WHERE DATEPART(YEAR,B.dtatende) = '2017'

GO

SELECT * FROM NV_TABLE
GO