-- TABELA TEMPORARIA SQL SERVER 


CREATE TABLE #TEMPORARIA (
ID INT IDENTITY (1,1) NOT NULL,
NOME VARCHAR (25),
IDADE INT 
)
GO

INSERT INTO #TEMPORARIA values ('Leonardo Medeiros',22)
GO
INSERT INTO #TEMPORARIA values ('Julia Alves',02)
GO

SELECT * FROM #TEMPORARIA