/* CRIAÇÃO DO CAMPO COMPQUERY TABELA RECEPCAO.DBO.PEPRELATORIOS CHAMADO 1644 */

USE RECEPCAO
GO

IF NOT EXISTS (
        SELECT 1 FROM syscolumns Coluna
    INNER JOIN sysobjects Tabela ON (Coluna.id = Tabela.id)
    WHERE Tabela.name = 'PEPRELATORIOS'
      and Coluna.name = 'QUERYCOMP')
	 
ALTER TABLE RECEPCAO.DBO.PEPRELATORIOS ADD QUERYCOMP TEXT
ELSE
    PRINT 'COLUNA JÁ EXISTE NA TABELA'


