USE RECEPCAO;
SELECT DISTINCT * FROM (
SELECT DISTINCT A.NOME, A.NOMEEQUIPE, A.IDADE, A.SEXO, A.PRONTUARIO, A.CNS, D.DESCRICAO MEDICACAO,
 CONVERT (VARCHAR(10), B.DATA,103) DataAtendimento FROM INDICADORES.VW_PEP_SIAB A
INNER JOIN SIABFACIL.PROCEDIMENTO_INDIVIDUAL B ON A.IDPEP = B.PESSOA_ID
INNER JOIN SIABFACIL.TIPO_PROCEDIMENTO_PARA_PROCEDIMENTO_INDIVIDUAL C ON B.ID = C.PROCEDIMENTO_INDIVIDUAL_ID
INNER JOIN SIABFACIL.TIPO_PROCEDIMENTO D ON C.TIPO_PROCEDIMENTO_ID = D.ID
WHERE D.ID IN (27,28, 29, 30, 31, 32)
) QRY


SELECT descricao, descricao FROM SIABFACIL.tipo_procedimento 
WHERE ID IN (27,28, 29, 30, 31, 32)