--ADOLESCENTES QUE NÃO PARTICIPARAM DE NENHUMA ATIVIDADE EM GRUPO
USE RECEPCAO;
SELECT DISTINCT C.NOME AS NOME_DO_PACIENTE, C.NOMEEQUIPE AS NOME_DA_EQUIPE, C.SEXO, CONVERT (VARCHAR(10), 
DATA_NASCIMENTO,103) AS DATA_NASCIMENTO, C.IDADE, C.MAE
FROM INDICADORES.VW_PEP_SIAB C
WHERE IDPEP NOT IN (SELECT ID_PARTICIPANTE FROM ATIVIDADE_PARTICIPANTES_GRUPO)
AND IDADE BETWEEN '12'AND'19'
and idsiab in (select * from openquery(siab,'select p.id from siabfacil.familia C
   inner join siabfacil.pessoa p on p.familia_id=c.id
   where bolsa_familia=TRUE'))
ORDER BY C.NOMEEQUIPE


