SELECT * FROM (
select * from openquery(siab,'SELECT DISTINCT 
	(SELECT CNES FROM CNES.LFCES004) "NUMERO CNES UNIDADE", 
	(SELECT NOME_FANTA FROM CNES.LFCES004) "NOME UNIDADE DE SAUDE",
	A.COD_AREA "EQUIPE",
	FA.MICROAREA "MICRO",
	PE.NOME "NOME",
	TO_CHAR(PE.DATA_NASCIMENTO, ''DD/MM/YYYY'') "NASCIMENTO",
	EXTRACT (YEAR FROM AGE(CURRENT_DATE, PE.DATA_NASCIMENTO)) "IDADE",
	PE.CNS "CNS",
	CASE WHEN PE.SEXO = TRUE THEN ''M'' ELSE ''F'' END "SEXO",
	CASE WHEN DIA.AMPUTACAO = TRUE THEN ''SIM'' ELSE ''NAO'' END "POSSUI AMPUTAÇAO"
	
FROM SIABFACIL.PESSOA PE
INNER JOIN SIABFACIL.FAMILIA FA ON PE.FAMILIA_ID = FA.ID
INNER JOIN SIABFACIL.SIAB_B_DIA DIA ON PE.ID = PERSON_ID
INNER JOIN SIABFACIL.PESSOA_GRUPO_DE_PESSOAS PGP ON  PE.ID = PGP.PESSOA_ID
INNER JOIN SIABFACIL.GRUPO_DE_PESSOAS GP ON PGP.GRUPO_DE_PESSOAS_ID = GP.ID
INNER JOIN SIABFACIL.PESSOA_GRUPO_DE_PESSOAS_LOG GPL ON PE.ID = GPL.PESSOA_ID
INNER JOIN CNES.LFCES038 A ON FA.PROF_ID = A.PROF_ID
INNER JOIN CNES.LFCES018 B ON A.PROF_ID = B.PROF_ID
WHERE PGP.GRUPO_DE_PESSOAS_ID = 7 -- DIABETICO
and dia.amputacao = true
AND GPL.DATA_SAIDA IS NULL
AND PE.DATA_DESATIVACAO IS NULL
AND FA.DATA_DESATIVACAO IS NULL

	GROUP BY A.COD_AREA, FA.COD_AREA, FA.MICROAREA, PE.NOME, PE, PE.CNS, PE.SEXO, PE.DATA_NASCIMENTO, FA.NUMERO,
	DIA.AMPUTACAO
	ORDER BY A.COD_AREA, FA.MICROAREA')
	) AS TEMP





