SET DATEFORMAT YMD
USE recepcao;
SELECT B.NOMEEQUIPE 'EQUIPE', C.NOME 'ESPECIALIDADE', B.NOME, B.DATA_NASCIMENTO, B.MAE 'NOME DA MÃE'  FROM PEPMOVIMENTOS A
INNER JOIN INDICADORES.VW_PEP_SIAB B ON A.CODPAC = B.IDPEP
INNER JOIN ESPECIALIDADES C ON A.ESPECIALIDADE = C.CODIGO
WHERE A.DATAFINALIZA BETWEEN '2016-01-01' AND '2016-06-30'
AND a.codmed in (1024,1025,2029,2036,2040,2045)
ORDER BY B.NomeEquipe, C.NOME





