--Beneficiários do bolsa família com data da última consulta
USE RECEPCAO;
SELECT DISTINCT C.NOME AS NOME_DO_PACIENTE, C.NOMEEQUIPE AS NOME_DA_EQUIPE, C.SEXO, CONVERT (VARCHAR(10), 
DATA_NASCIMENTO,103) AS DATA_NASCIMENTO, C.MAE,
(SELECT TOP 1 CONVERT (VARCHAR(10), dtatende,103 )  FROM pepmovimentos x where x.codpac=c.idpep order by codigo desc) AS DATA_ULTIMO_ATENDIMENTO
FROM INDICADORES.VW_PEP_SIAB C
INNER JOIN DADOS_COMPLEMENTARES_LCT A ON A.id_codpac = C.IDPep
INNER JOIN DADOS_COMPLEMENTARES B ON A.ID_DADOS = B.ID
WHERE A.ID_DADOS = 19
AND A.CHK = 'S'
ORDER BY C.NOMEEQUIPE


