/*SMALLINT PERMITE NÚMEROS INTEIROS DE -32768 A 32768 E OCUPA 2 BYTES*/
/*IDENTITY INSERE AUTOMATICAMENTE O VALOR NA COLUNA, NESTE CASO, INICIANDO EM 1 E AUMENTANDO DE 1 EM 1*/
/*UNIQUE FAZ COM QUE NÃO SEJA PERMITIDO VALORES REPETIDOS NA COLUNA*/

USE biblioteca;

CREATE TABLE livros
(
id_livro SMALLINT PRIMARY KEY IDENTITY (1,1),
nome_livro VARCHAR (50) NOT NULL,
isbn INT NOT NULL UNIQUE,
data_pub DATE NOT NULL,
preco_livro MONEY NOT NULL,
id_autor INT NOT NULL,
);