--Crianças entre 1 e 5 anos com data da última consulta
USE RECEPCAO;
SELECT DISTINCT C.NOME AS NOME_DO_PACIENTE, C.NOMEEQUIPE AS NOME_DA_EQUIPE, C.SEXO, C.IDADE, CONVERT (VARCHAR(10), DATA_NASCIMENTO,103) AS DATA_NASCIMENTO, C.MAE,
(SELECT TOP 1 CONVERT (VARCHAR(10), dtatende,103 )  FROM pepmovimentos x where x.codpac=c.idpep order by codigo desc) AS DATA_ULTIMO_ATENDIMENTO
FROM INDICADORES.VW_PEP_SIAB C
WHERE C.IDADE BETWEEN 1 AND 5 -- informar a idade
ORDER BY C.NOMEEQUIPE

