USE RECEPCAO;
SELECT F.NOME, C.NomeEquipe, C.IDADE, C.CNS, A.DATAFINALIZA, D.NOME PROFISSIONAL, E.DESCR, E.CID10 FROM PEPMOVIMENTOS A
INNER JOIN MEDICOPRONTUARIO B ON A.CODIGO = B.IDMovimento
LEFT JOIN INDICADORES.VW_PEP_SIAB C ON A.CODPAC = C.IDPEP
INNER JOIN MEDICOS D ON A.CODMED = D.CODIGO
INNER JOIN CID E ON E.ID = B.CID10
INNER JOIN PACIENTES F ON A.CODPAC = F.CODIGO

WHERE E.CID10 = 'T512'

