SELECT * FROM (
SELECT DISTINCT B.NOME, B.NomeEquipe, B.mae, B.cns, B.IDADE
FROM PESSOA_GRUPO_DE_PESSOAS A
INNER JOIN INDICADORES.VW_PEP_SIAB B ON A.COD_PAC = B.IDPEP
WHERE A.GRUPO_DE_PESSOAS_ID = 7
AND A.ATIVO <> 'N'
and IDPep not in (
select codpac from PEPMOVIMENTOS C 
INNER JOIN PE_DIABETICO D ON C.CODIGO = D.MOV_ID
AND D.AVALIACAO_PE_DIABETICO IS NOT NULL
AND D.AVALIACAO_PE_DIABETICO <> ''
)
) AS TEMP