USE LM_VEICULOS
GO

CREATE MASTER KEY ENCRYPTION
BY PASSWORD = '!@#leo' 
GO


CREATE CERTIFICATE lmCERTIFICATE
ENCRYPTION BY PASSWORD = '!@#leo'
WITH SUBJECT = 'lmCERTIFICATE'
GO

CREATE SYMMETRIC KEY ChaveLM
WITH ALGORITHM = AES_256
ENCRYPTION BY CERTIFICATE lmCERTIFICATE


SELECT * FROM SYS.symmetric_keys
GO
SELECT * FROM SYS.certificates
GO

OPEN SYMMETRIC KEY ChaveLM 
 DECRYPTION BY CERTIFICATE lmCERTIFICATE  WITH PASSWORD = '!@#leo'
 GO

 
  SELECT    *
 ,   salarioDescriptografado = CAST (DECRYPTBYKEY(salario) AS varchar(50))
 FROM      funcionarios
 GO

 CLOSE SYMMETRIC KEY ChaveLM


 
