SET DATEFORMAT DMY

DECLARE @DATAINI DATETIME
DECLARE @DATAFIM DATETIME

SET @DATAINI = '01/01/2016'
SET @DATAFIM = '27/07/2017 23:59:59'

SELECT A.NOME,D.NOME [UNIDADE DE VINCULO], E.NOME [AREA], F.NOME [MICROAREA],
(SELECT NOME FROM PESSOA.PROFISSIONAL AA WHERE AA.ID = B.ID_PROFISSIONAL) [PROFISSIONAL BARTHEL INICIAL],
B.PONTUACAO [BARTHEL INICIAL],B.DATAHORA [DATA BARTHEL INCIAL],
(SELECT NOME FROM PESSOA.PROFISSIONAL AA WHERE AA.ID = C.ID_PROFISSIONAL) [PROFISSIONAL BARTHEL FINAL],
C.PONTUACAO [BARTHEL FINAL],B.DATAHORA [DATA BARTHEL FINAL],B.ALIMENTACAO [ALIMENTACAO], 
B.BANHO [BANHO],B.TOILET [TOALETE PESSOAL], B.VESTIR [VESTUARIO], B.INTESTINO [CONTROLE INTESTINO], 
B.URINARIO [CONTROLE BEXIGA], B.ATIVIDADEROTINEIRA[LOCOMOCAO ATE O BANHEIRO], 
B.TRANSFERENCIA [TRANSFERENCIA DA CAMA PARA CADEIRA], B.MOBILIDADE [MOBILIDADE DE AMPUTAÇÃO] , 
B.ESCALA [SUBIR ESCADAS], B.PONTUACAO [PONTUACAO]

FROM PESSOA.PACIENTE A
INNER JOIN ATENDIMENTO.BARTHEL B ON A.ID = B.ID_PROFISSIONAL
AND B.ID IN (SELECT MIN(ID) FROM ATENDIMENTO.BARTHEL AA GROUP BY ID_PACIENTE)
AND B.DATAHORA >= @DATAINI AND B.DATAHORA <= @DATAFIM 
INNER JOIN ATENDIMENTO.BARTHEL C ON A.ID = C.ID_PROFISSIONAL 
AND C.ID IN (SELECT MAX(ID) FROM ATENDIMENTO.BARTHEL AA GROUP BY ID_PACIENTE)
AND C.DATAHORA >= @DATAINI AND C.DATAHORA <= @DATAFIM
INNER JOIN SISTEMA.UNIDADES D ON A.ID_UNIDADEVINCULO = D.ID
INNER JOIN SISTEMA.AREA E ON A.ID_AREA = E.ID
INNER JOIN SISTEMA.MICROAREA F ON A.ID_AREA = F.ID
