SELECT * FROM (
SELECT DISTINCT (C.NOME), C.NomeEquipe, C.IDADE, C.MAE, C.CNS, convert(varchar(max),A.MOTIVO) AS MOTIVO,
(SELECT TOP 1 DataFinaliza FROM PEPMOVIMENTOS PM WHERE PM.CODPAC = C.IDPEP ORDER BY DATAFINALIZA DESC) AS DataUltimaConsulta, 
A.DATA_FINALIZACAO FROM PESSOA_GRUPO_DE_PESSOAS A
INNER JOIN PEPMOVIMENTOS B ON A.COD_PAC = B.CODPAC
INNER JOIN INDICADORES.VW_PEP_SIAB C ON A.COD_PAC = C.IDPEP
WHERE A.GRUPO_DE_PESSOAS_ID = 5
AND ATIVO = 'N'
AND (DATENAME(month,A.Data_Finalizacao) = DATENAME(month, GETDATE())
and DATENAME(YEAR,A.Data_Finalizacao) = DATENAME(YEAR, GETDATE()))
) AS TEMP