-- CRIA TABELA
USE RECEPCAO
GO
SET NOCOUNT ON 
IF NOT EXISTS(
	SELECT 1 FROM RECEPCAO.SYS.TABLES WHERE NAME = 'IC_Tamanhos')
BEGIN
	EXEC('
			CREATE TABLE IC_Tamanhos(
			CODIGO INT IDENTITY(1,1) PRIMARY KEY,
			DESCRICAO VARCHAR(60) NOT NULL,
			STATUS BIT NOT NULL DEFAULT 1)
	')
	PRINT 'Criada tabela RECEPCAO.DBO.IC_Tamanhos'
END ELSE
BEGIN
  PRINT 'Ja Existe a tabela RECEPCAO.DBO.IC_Tamanhos'
END

-- ADICIONA COLUNA
USE RECEPCAO
IF NOT EXISTS (
	SELECT 1 FROM syscolumns Coluna 
    INNER JOIN sysobjects Tabela ON (Coluna.id = Tabela.id) 
    WHERE Tabela.name = 'param_ext'
      and Coluna.name = 'FaixaEtariaAlter')
BEGIN
  ALTER TABLE param_ext ADD FaixaEtariaAlter BIT DEFAULT 0 NOT NULL;
  PRINT 'Coluna FaixaEtariaAlter criada na tabela param_ext'      
END ELSE
BEGIN
  PRINT 'Coluna FaixaEtariaAlter ja existe na tabela param_ext'
END 

--CRIA PROCEDURE OU FUNCTION
USE RECEPCAO
GO
IF NOT EXISTS(
	SELECT 1 FROM Information_schema.Routines WHERE Specific_schema = 'dbo'
										      AND specific_name = 'Fr_RelMapaTriagem'
											  AND Routine_Type = 'FUNCTION')
BEGIN
	EXEC('
			CREATE FUNCTION dbo.Fr_RelMapaTriagem(@FICHA INT, @TIPO CHAR(1))
			RETURNS VARCHAR(100)
			AS
			BEGIN
			--DECLARE @FICHA INT = 57
			--DECLARE @TIPO CHAR(1) = ''U'' 
			DECLARE @DATA DATETIME
			DECLARE @INFO VARCHAR(100)
			IF (@TIPO = ''P'')
				SET @DATA = (SELECT TOP 1 DATA_TRIAGEM FROM RECEPCAO.DBO.MED_TRIAGEMNUTRICIONAL
				WHERE FICHA = @FICHA
				ORDER BY DATA_TRIAGEM ASC)
			IF (@TIPO = ''U'')
				SET @DATA = (SELECT TOP 1 DATA_TRIAGEM FROM RECEPCAO.DBO.MED_TRIAGEMNUTRICIONAL
				WHERE FICHA = @FICHA
				ORDER BY DATA_TRIAGEM DESC)
			IF (@TIPO = ''D'')
				SET @INFO = (SELECT TOP 1 DIAGINICIAL FROM RECEPCAO.DBO.MED_TRIAGEMNUTRICIONAL WHERE FICHA = @FICHA ORDER BY DATA_TRIAGEM DESC)
			IF (@TIPO = ''O'')
				SET @INFO = (SELECT TOP 1 OBSERVACOES FROM RECEPCAO.DBO.MED_TRIAGEMNUTRICIONAL WHERE FICHA = @FICHA ORDER BY DATA_TRIAGEM DESC)

			IF (@TIPO IN(''P'',''U''))
				SET @INFO = (CONVERT(VARCHAR(10),@DATA,103))
	
			RETURN(@INFO)
			--SELECT CONVERT(VARCHAR(10),@DATA,103) 
		END
	')
	PRINT 'Criada Function RECEPCAO.DBO.Fr_RelMapaTriagem'
END ELSE
BEGIN
  PRINT 'Ja Existe a Function RECEPCAO.DBO.Fr_RelMapaTriagem'
END
