--QUANTIDADE DE PACIENTES QUE RESIDEM FORA DO MUNICIPIO ATENDIDOS PELO PEP
USE RECEPCAO;
SELECT * from pacientes 

--MUNICIPIOS EM QUE RESIDEM
USE RECEPCAO
SELECT * FROM (
SELECT DISTINCT A.NOME, A.nomemun [Município em que reside], A.CPF,
CONVERT(VARCHAR(10),A.DTNASC, 103) [Data de Nascimento], A.MAE, A.CARTAOSUS, A.COD_FAMILIA Prontuario FROM PACIENTES A
INNER JOIN PEPMOVIMENTOS B ON A.CODIGO = B.CODPAC
WHERE A.municipio <> 330455
AND A.nomemun <> 'SAO PAULO') QRY




