--N18 E I50
USE RECEPCAO;
SELECT DISTINCT C.NOME AS NOME_DO_PACIENTE, C.NOMEEQUIPE AS NOME_DA_EQUIPE, C.SEXO, CONVERT (VARCHAR(10), 
DATA_NASCIMENTO,103) AS DATA_NASCIMENTO, C.MAE, D.CID10, D.DESCR,
(SELECT TOP 1 CONVERT (VARCHAR(10), dtatende,103 )  FROM pepmovimentos x where x.codpac=c.idpep order by codigo desc) AS DATA_ULTIMO_ATENDIMENTO
FROM INDICADORES.VW_PEP_SIAB C
INNER JOIN PEPMOVIMENTOS A ON C.IDPEP = A.CODPAC
INNER JOIN PepMovimentos_CID B ON A.CODIGO = B.id_PepMovimentos
INNER JOIN CID D ON B.id_cid = D.ID
WHERE D.ID in (6115, 3886)  --Informar id da tabela cid
ORDER BY C.NOMEEQUIPE


--SELECT * FROM CID
--WHERE CID10 = 'i50'