
use RECEPCAO
go


SELECT DISTINCT C.NOME, D.CID10 FROM PEPMOVIMENTOS A
INNER JOIN PEPMOVIMENTOS_CID B ON B.ID_PEPMOVIMENTOS = A.CODIGO
INNER JOIN PACIENTES C ON A.CODPAC = C.CODIGO
INNER JOIN CID D ON B.ID_CID = D.ID
WHERE D.CID10 between 'C00' and 'C97'
union
SELECT DISTINCT C.NOME, D.CID10 FROM PEPMOVIMENTOS A
INNER JOIN PEPMOVIMENTOS_CID B ON B.ID_PEPMOVIMENTOS = A.CODIGO
INNER JOIN PACIENTES C ON A.CODPAC = C.CODIGO
INNER JOIN CID D ON B.ID_CID = D.ID
WHERE D.CID10 in('N17','N18')
union
SELECT DISTINCT C.NOME, D.CID10 FROM PEPMOVIMENTOS A
INNER JOIN PEPMOVIMENTOS_CID B ON B.ID_PEPMOVIMENTOS = A.CODIGO
INNER JOIN PACIENTES C ON A.CODPAC = C.CODIGO
INNER JOIN CID D ON B.ID_CID = D.ID
WHERE D.CID10 in ('I11','I10','I20')
union
SELECT DISTINCT C.NOME, D.CID10 FROM PEPMOVIMENTOS A
INNER JOIN PEPMOVIMENTOS_CID B ON B.ID_PEPMOVIMENTOS = A.CODIGO
INNER JOIN PACIENTES C ON A.CODPAC = C.CODIGO
INNER JOIN CID D ON B.ID_CID = D.ID
WHERE D.CID10 in ('E11','E10')

ORDER BY C.nome




/*--Cid C 00 a C 97. 
--N 17 e n18 
--I 11, i 10 e I 20
E11 e E 10*/