USE RECEPCAO;

--EXECUTAR PRIMEIRO ESSE
SELECT * FROM PACIENTES
WHERE NOME = 'Carla Regina Suarez de carlos' --DIGITAR O NOME DO PACIENTE, PEGAR O CAMPO CODIGO DESSA TABELA

SELECT * FROM exames.colpocitologia
WHERE CODPAC = 22758 --DIGITAR AQUI O CODIGO OBTIDO DA TABELA ACIMA



