-- COMPLETUDE DE DADOS DA FICHA DE CADASTRO INDIVIDUAL
SELECT DISTINCT 
	(SELECT NOME_FANTA FROM CNES.LFCES004) "NOME_UNIDADE_DE_SAUDE",
	--DADOS DA UNIDADE E ACS
	B.NM_REFERENCIA "NOME EQUIPE DE SAUADE",
	A.COD_CNS "CARTAO SUS PROFISSIONAL",
	A.NOME_PROF "NOME ACS",
	FA.COD_AREA "EQUIPE",
	FA.MICROAREA "MICROAREA",
	FA.NUMERO "NUMERO FAMILIA",
	PP.CNS "CARTAO SUS",
	PP.NOME "NOME DA PESSOA",
	PP.APELIDO "NOME SOCIAL",
	TO_CHAR (PP.DATA_NASCIMENTO, 'DD/MM/YYYY') "DATA DE NACIMENTO",
	CASE WHEN PP.SEXO = TRUE THEN 'M' ELSE 'F' END "SEXO",
	PF.DESCRICAO "RELACAO DE PARENTESCO COM RESPRESENTANTE",
	C.DS_RACA "RAÇA COR",
	PP.NIS "NUMERO DO NIS",
	PP.NOME_DA_MAE "NOME DA MAE",
	CASE PP.MAE_DESCONHECIDA 
	WHEN TRUE THEN 'SIM'
	WHEN FALSE THEN 'NAO' ELSE 'NAO INFORMADO' END "MAE DESCONHECIDA",
	CASE WHEN NA.DESCRICAO IS NULL THEN 'NAO INFORMADO' ELSE NA.DESCRICAO END "NACIONALIDADE",
	E.DS_PAIS "PAIS_DE_NASCIMENTO",
	PP.TELEFONE "CELULAR",
	PP.TELEFONE_2 "CONTATO",
	PP.TELEFONE_3 "CONTATO",
	PP.EMAIL "EMAIL",
	D.NOME_MUN "MUNICIPIO DE NACIMENTO",
	CASE WHEN EC.DESCRICAO IS NULL THEN 'NAO INFORMADO' ELSE EC.DESCRICAO END "ESTADO CIVIL",
	CASE WHEN OC.DESCRICAO IS NULL THEN 'NAO INFORMADO' ELSE OC.DESCRICAO END "PROFISSAO",
	CASE WHEN PP.FREQUENTA_ESCOLA = TRUE THEN 'SIM' ELSE 'NAO' END "FRENQUENTA ESCOLA",
	CASE WHEN ES.DESCRICAO IS NULL THEN 'NAO_INFORMADO' ELSE ES.DESCRICAO END "ESCOLARIDADE",
	CASE WHEN TR.ID IS NULL THEN 'NAO_INFORMADO' ELSE ST.DESCRICAO END "SITUACAO DE TRABALHO",
	CASE WHEN RC.DESCRICAO IS NULL THEN 'NAO_INFORMADO' ELSE RC.DESCRICAO END "CRIANCAS DE 0 A 9 ANOS COM QUEM FICA?",
	CASE WHEN PP.FREQUENTA_BENZEDEIRA = TRUE THEN 'SIM' ELSE 'NAO' END"FREQUENTA BEZENDEIRA/CURANDEIRA",
	CASE WHEN PP.GRUPO_COMUNITARIO = TRUE THEN 'SIM' ELSE 'NAO' END "PARTICIPA DE GRUPO COMUNITARIO",
	PS.NOME "POSSUI PLANO DE SAUDE",
	PP.POVO_COMUNIDADE_TRADICIONAL "E MEMBRO DE POVO OU COMUNIDADE TRADICIONAL",
	CASE WHEN OS.DESCRICAO IS NULL THEN 'NAO INFORMADO' ELSE OS.DESCRICAO END "ORIENTACAO SEXUAL",
	SP.DESCRICAO "SOBRE SEU PESO VOCE SE CONSIDERA",
	CASE WHEN GP.ID = 1 THEN 'SIM' END "ALCOOLISMO",
	case when gp.id = 4 THEN 'SIM' END "DOENCA DE CHAGAS",
	CASE WHEN GP.ID = 2 THEN 'SIM' END "EPILEPSIA",
	CASE WHEN GP.ID = 7 THEN 'SIM' END "DIABETES",
	CASE WHEN GP.ID = 5 THEN 'SIM' END "GESTANTE",
	PP.MATERNIDADE_REFERENCIA "MATERNIDADE DE REFERENCIA GEST",
	CASE WHEN GP.ID = 3 THEN 'SIM' END "HANSENIASE",
	CASE WHEN GP.ID = 6 THEN 'SIM' END "HIPERTENSAO ARTERIAL",
	CASE WHEN GP.ID = 12 THEN 'SIM'END "MALARIA",
	CASE WHEN GP.ID = 8 THEN 'SIM' END "TUBERCULOSE",
	CASE WHEN GP.ID = 21 THEN 'SIM'END "TABAGISMO",
	CASE WHEN GP.ID = 10 THEN 'SIM'END "DEFICIENCIA FISICA",
	CASE WHEN GP.ID = 0 THEN 'SIM' END "DOENCA MENTAL",
	CASE PP.DEF_VISUAL WHEN TRUE THEN 'SIM' END "DEFICIENCIA VISUAL",
	CASE PP.DEF_AUDITIVA WHEN TRUE THEN 'SIM' END "DEFICIENCIA AUDITIVA",
	CASE PP.AVC_DERRAME WHEN TRUE THEN 'SIM' END "TEVE AVC DERRAME",
	CASE PP.INFARTO WHEN TRUE THEN 'SIM' END "TEVE INFARTO",
	RE.DESCRICAO "DOENCA RESPIRATORIA",
	DC.DESCRICAO "DOENCA CARDIACA",
	CASE PP.TEM_TEVE_CANCER WHEN TRUE THEN 'SIM' END "TEM OU TEVE CANCER",
	TC.DESCRICAO "TIPO DE CANCER",
	DR.DESCRICAO "DOENCA DOS RINS",
	PP.CANCER_OUTRO "CANCER OUTRO",
	CASE PP.TEVE_INTERNACAO WHEN TRUE THEN 'SIM' END "TEVE INTERNACAO",
	PP.TEVE_INTERNACAO_MOTIVO "MOTIVO DA INTERNACAO",
	CASE PP.TRATAMENTO_MENTAL WHEN TRUE THEN 'SIM' END "FEZ OU FAZ TRATAMENTO COM SIQUIATRA",
	CASE PP.DOMICILIADO WHEN TRUE THEN 'SIM' END "ESTA ACAMADO",
	CASE PP.DOMICILIADO_CUIDADOR WHEN TRUE THEN 'SIM' END "DOMICILIADO TEM CUIDADOR",
	PP.PLANTAS_MEDICINAIS "USA PLANTAS MEDICINAIS",
	CASE PP.PRATICAS_INTEGRATIVAS
	WHEN TRUE THEN 'SIM' 
	WHEN FALSE THEN 'NAO' END "USA OUTRAS PRATICAS INTEGRATIVAS",
	PP.CONDICAO_SAUDE_1 "OUTRAS CONDICOES DE SAUDE 1",
	PP.CONDICAO_SAUDE_2 "OUTRAS CONDICOES DE SAUDE 2",
	PP.CONDICAO_SAUDE_3 "OUTRAS CONDICOES DE SAUDE 3",
	TO_CHAR(PP.DATA_ATIVACAO, 'DD/MM/YYYY') "DATA CADASTRO"
	
FROM SIABFACIL.PESSOA PP

INNER JOIN SIABFACIL.FAMILIA FA ON FA.ID = PP.FAMILIA_ID
INNER JOIN SIABFACIL.POSICAO_FAMILIAR PF ON PF.ID = PP.POSICAO_FAMILIAR_ID
LEFT JOIN SIABFACIL.NACIONALIDADE NA ON NA.ID = PP.NACIONALIDADE_ID
LEFT JOIN SIABFACIL.ESTADO_CIVIL EC ON PP.ESTADO_CIVIL_ID = EC.ID
LEFT JOIN SIABFACIL.ESCOLARIDADE ES ON PP.ESCOLARIDADE_ID = ES.ID
LEFT JOIN SIABFACIL.PLANO_DE_SAUDE PS ON PS.ID = PP.PLANO_DE_SAUDE_ID --PLANO DE SAUE
LEFT JOIN SIABFACIL.SITUACAO_TRABALHO TR ON PP.SITUACAO_TRABALHO_ID = TR.ID
LEFT JOIN SIABFACIL.RESPONSAVEL_CRIANCA RC ON PP.RESPONSAVEL_CRIANCA_ID = RC.ID
LEFT JOIN SIABFACIL.PESSOA_DOENCA_CARDIACA DCA ON PP.ID = DCA.PESSOA_ID
LEFT JOIN SIABFACIL.DOENCA_CARDIACA DC ON DCA.DOENCA_CARDIACA_ID = DC.ID -- DOENCA CARDIACA
LEFT JOIN SIABFACIL.PESSOA_DOENCA_RESPIRATORIA DRE ON PP.ID = DRE.PESSOA_ID
LEFT JOIN SIABFACIL.DOENCA_RESPIRATORIA RE ON DRE.DOENCA_RESPIRATORIA_ID = RE.ID -- DOENCA RESPIRATORIA
LEFT JOIN SIABFACIL.PESSOA_DOENCA_RINS PDR ON PP.ID = PDR.PESSOA_ID
LEFT JOIN SIABFACIL.DOENCA_RINS DR ON PDR.DOENCA_RINS_ID = DR.ID -- DOENCA RINS
LEFT JOIN SIABFACIL.TIPO_CANCER TC ON 'PP.CANCER' = 'TC.ID' -- TIPOS DE CANCER
LEFT JOIN SIABFACIL.ORIENTACAO_SEXUAL OS ON PP.ORIENTACAO_SEXUAL_ID = OS.ID
LEFT JOIN SIABFACIL.PESSOA_GRUPO_DE_PESSOAS PGP ON  PP.ID = PGP.PESSOA_ID
LEFT JOIN SIABFACIL.GRUPO_DE_PESSOAS GP ON PGP.GRUPO_DE_PESSOAS_ID = GP.ID
LEFT JOIN SIABFACIL.SITUACAO_TRABALHO ST ON ST.ID = PP.SITUACAO_TRABALHO_ID
LEFT JOIN SIABFACIL.OCUPACAO OC ON OC.ID = PP.OCUPACAO_ID
LEFT JOIN SIABFACIL.SITUACAO_PESO SP ON PP.SITUACAO_PESO_ID = SP.ID

LEFT JOIN CNES.LFCES018 A ON A.PROF_ID = FA.PROF_ID
LEFT JOIN CNES.LFCES037 B ON B.COD_AREA = FA.COD_AREA
LEFT JOIN CNES.NFCES038 C ON C.CD_RACA = PP.CD_RACA -- BUSCA RACA COR
LEFT JOIN CNES.NFCES005 D ON FA.COD_MUN = D.COD_MUN -- BUSCA MUNICIPIOS
LEFT JOIN CNES.NFCES036 E ON PP.PAIS_NASCIMENTO_ID = E.CD_PAIS

WHERE PP.FAMILIA_ID IS NOT NULL
AND PP.DATA_DESATIVACAO IS NULL
AND B.CO_EQUIPE IS NOT NULL
