--Residentes fora da área de abrangência
SELECT COUNT(1) [CONSULTAS MEDICAS FORA DA ÁREA DE ABRANGÊNCIA]
FROM PepMovimentos A
     INNER JOIN PACIENTES B ON(A.codpac = B.codigo)
     INNER JOIN Especialidades C ON(A.Especialidade = C.Codigo)
WHERE A.Status = 'F'
      AND C.Codigo = 323
      AND B.cod_familia = 'FORA DE AREA'
-------------------------------------------------------

--ATENDIMENTO MEDICO A RESIDENTES DENTRO DA AREA DE ABRANGENCIA POR FX ETARIA


select  EQUIPE,A [<1], B [1 A 4],C [5 A 9], D [10 A 14], E [15 A 19], F [20 A 39], G [40 A 49],
H [50 A 59], I [>60], A+B+C+D+E+F+G+H+I [TOTAL] from (
SELECT  B.nomeequipe [EQUIPE], 
 SUM(CASE WHEN B.idade < 1 THEN 1 ELSE 0 END) 'A',
 SUM(CASE WHEN B.idade BETWEEN 1 AND 4 THEN 1 ELSE 0 END) 'B',
 SUM(CASE WHEN B.idade BETWEEN 5 AND 9 THEN 1 ELSE 0 END) 'C',
 SUM(CASE WHEN B.idade BETWEEN 10 AND 14 THEN 1 ELSE 0 END) 'D',
 SUM(CASE WHEN B.idade BETWEEN 15 AND 19 THEN 1 ELSE 0 END) 'E',
 SUM(CASE WHEN B.idade BETWEEN 20 AND 39 THEN 1 ELSE 0 END) 'F',
 SUM(CASE WHEN B.idade BETWEEN 40 AND 49 THEN 1 ELSE 0 END) 'G',
 SUM(CASE WHEN B.idade BETWEEN 50 AND 59 THEN 1 ELSE 0 END) 'H',
 SUM(CASE WHEN B.idade >60 THEN 1 ELSE 0 END) 'I'
FROM PepMovimentos A
INNER JOIN Indicadores.vw_pep_siab B ON (A.codpac = B.IDPep)
WHERE A.Status = 'F'
AND A.Especialidade = 323
GROUP BY B.NomeEquipe)aa

-------------------------------------------------------
--TIPO DE ATENDIMENTO MEDICO E DE ENFERMEIRO
SELECT   B.NomeEquipe [EQUIPE],
	SUM(CASE WHEN B.CODIGO = 'ABP004' THEN 1 ELSE 0 END) 'PUERICULTURA',
	SUM(CASE WHEN B.CODIGO = 'ABP001' THEN 1 ELSE 0 END) 'PRÉ-NATAL',
	SUM(CASE WHEN B.CODIGO = 'ABP022' THEN 1 ELSE 0 END) 'PREV CANCER UTERO',
	SUM(CASE WHEN B.CODIGO = 'ABP020' THEN 1 ELSE 0 END) 'DST/AIDS',
	SUM(CASE WHEN B.CODIGO = 'ABP006' THEN 1 ELSE 0 END) 'DIABETES',
	SUM(CASE WHEN B.CODIGO = 'ABP005' THEN 1 ELSE 0 END) 'HA',
	SUM(CASE WHEN B.CODIGO = 'ABP018' THEN 1 ELSE 0 END) 'HANSENÍASE',
	SUM(CASE WHEN B.CODIGO = 'ABP017' THEN 1 ELSE 0 END) 'TUBERCULOSE',
	SUM(CASE WHEN B.CODIGO = 'ABP012' THEN 1 ELSE 0 END) 'USUARIO DE ALCOOL', --PMA2C
	SUM(CASE WHEN B.CODIGO = 'ABP013' THEN 1 ELSE 0 END) 'USUARIO DE DROGAS', --PMA2C
	SUM(CASE WHEN B.CODIGO = 'ABP014' THEN 1 ELSE 0 END) 'SAUDE MENTAL' --PMA2C
FROM PepMovimentos A
INNER JOIN Indicadores.vw_pep_siab B ON (A.codpac = B.IDPep)
INNER JOIN pessoa_grupo_de_pessoas C ON (C.COD_PAC = B.IDPep)







