USE RECEPCAO
--VISITAS
SET DATEFORMAT DMY
SELECT 'MES '+ CONVERT(VARCHAR(2),p.dtatende,1) [DATA_VISITA],m.nome [NOME],COUNT(MONTH(p.dtatende)) [QTDE_VISITAS]  FROM PEPMOVIMENTOS P
INNER JOIN RECEPCAO.dbo.medicos M ON (P.CODMED = M.CODIGO)
WHERE P.MOVIMENTO = 3 AND M.CODIGO IN (77,
78,
84,
86,
123,
136,
143,
153)
AND YEAR(dtatende) = '2017' 
GROUP BY CONVERT(VARCHAR(2),p.dtatende,1),m.nome
ORDER BY [DATA_VISITA]



--CONSULTAS
SET DATEFORMAT DMY
SELECT 'MES '+ CONVERT(VARCHAR(2),p.dtatende,1) [DATA_CONSULTA],m.nome [NOME],COUNT(MONTH(p.dtatende)) [QTDE_CONSULTAS]  FROM PEPMOVIMENTOS P
INNER JOIN RECEPCAO.dbo.medicos M ON (P.CODMED = M.CODIGO)
WHERE P.MOVIMENTO <> 3 AND M.CODIGO IN (77,
78,
84,
86,
123,
136,
143,
153)
AND YEAR(dtatende) = '2017' AND M.situacao = 'A' AND P.Status = 'F'
GROUP BY CONVERT(VARCHAR(2),p.dtatende,1),m.nome
ORDER BY [DATA_CONSULTA]



--ATIVIDADE COLETIVA
SELECT  [DATA_ATIVIDADE],[PROFISSIONAIS], SUM([QTDE_ATIVIDADE]) [QTDE_ATIVIDADE] FROM (
	SELECT  'MÊS ' + CONVERT(VARCHAR(2),data_atividade,1) [DATA_ATIVIDADE],U.NOMECOMPLETO
	[PROFISSIONAIS], COUNT(MONTH(data_atividade)) [QTDE_ATIVIDADE] 
	FROM ATIVIDADE_GRUPO A
	INNER JOIN ACESSO.DBO.Usuarios U ON (A.id_prof_resp = U.Codigo)
	WHERE YEAR(DATA_ATIVIDADE) = '2017'

AND id_prof_resp IN (SELECT CODIGO FROM ACESSO.DBO.USUARIOS WHERE CODIGO IN (3726,3722,
3727,4802,3721,4813,3764))
GROUP BY U.NOMECOMPLETO,data_atividade) as temp
group by data_atividade,[PROFISSIONAIS]
ORDER BY [DATA_ATIVIDADE]







