USE RECEPCAO
GO
DROP USER HMSC
GO
CREATE USER HMSC FROM LOGIN HMSC
GO
GRANT SELECT, UPDATE, DELETE, INSERT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE SCHEMA, ALTER, EXECUTE,CONNECT  TO HMSC
USE ACESSO
GO
DROP USER HMSC
GO
CREATE USER HMSC FROM LOGIN HMSC
GO
GRANT SELECT, UPDATE, DELETE, INSERT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE SCHEMA, ALTER, EXECUTE,CONNECT  TO HMSC
USE BCOSANGUE
GO
DROP USER HMSC
GO
CREATE USER HMSC FROM LOGIN HMSC
GO
GRANT SELECT, UPDATE, DELETE, INSERT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE SCHEMA, ALTER, EXECUTE,CONNECT  TO HMSC
USE CADASTRO
GO
DROP USER HMSC
GO
CREATE USER HMSC FROM LOGIN HMSC
GO
GRANT SELECT, UPDATE, DELETE, INSERT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE SCHEMA, ALTER, EXECUTE,CONNECT  TO HMSC
USE CIRURGIA
GO
DROP USER HMSC
GO
CREATE USER HMSC FROM LOGIN HMSC
GO
GRANT SELECT, UPDATE, DELETE, INSERT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE SCHEMA, ALTER, EXECUTE,CONNECT  TO HMSC
USE INTEGRACAO
GO
DROP USER HMSC
GO
CREATE USER HMSC FROM LOGIN HMSC
GO
GRANT SELECT, UPDATE, DELETE, INSERT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE SCHEMA, ALTER, EXECUTE,CONNECT  TO HMSC
USE MATERIAS
GO
DROP USER HMSC
GO
CREATE USER HMSC FROM LOGIN HMSC
GO
GRANT SELECT, UPDATE, DELETE, INSERT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE SCHEMA, ALTER, EXECUTE,CONNECT  TO HMSC
