USE DBMec
GO

/*ALTERA DATA DE ALTA PACIENTE iVAN DOS SANTOS FONTES*/
SELECT * FROM Atendimento.Alta
-- UPDATE Atendimento.Alta SET DATA = '2018-03-02 00:00:00.000'
WHERE ID_Paciente = 15414


/* deleta registro de alta duplicado do paciente ADONAI ELOM DE CARVALHO HOUNWANOU */
select * from Atendimento.Alta
-- DELETE FROM Atendimento.Alta
where  ID = 11817

/* ALTERA O TIPO DE ALTA PARA O PACIENTE ANGELA DAVID INACIO DA SILVEIRA*/
SELECT * FROM Atendimento.Alta
-- UPDATE Atendimento.Alta SET TIPOALTA = 'CB'
WHERE ID_Paciente = 8431


/* ALTERADO O TIPO DE ALTA E DATA DA ALTA PARA O PACIENTE ANA MARIA MACHADO*/
SET DATEFORMAT DMY
SELECT * FROM Atendimento.ALTA
-- UPDATE Atendimento.ALTA SET DATA = '21-02-2018 00:00:00.000', TIPOALTA = 'PB'
WHERE ID_Paciente = 12828


/* PACIENTE HELOISA SANTO SILVA POSSUI APENAS UM REGISTRO DE ALTA*/
SELECT * FROM Atendimento.Alta
WHERE ID_Paciente = 15304


/* ALTERADO O TIPO DE ALTA PARA O PACIENTE DURVAL DOS REIS*/
SELECT * FROM Atendimento.Alta
-- UPDATE ATENDIMENTO.ALTA SET TIPOALTA = 'PB'
WHERE ID_Paciente = 14143

/* ALTERADO O TIPO DE ALTA PARA O PACIENTE MIREYA ANDREOTTA PICOS*/
SELECT * FROM Atendimento.Alta
-- UPDATE ATENDIMENTO.ALTA SET TIPOALTA = 'PB'
WHERE ID_Paciente = 8496

/* ALTERADO O TIPO DE ALTA E DATA DA ALTA PARA O PACIENTE MARIA CRISTINA DO NASCIMENTO*/
SELECT * FROM Atendimento.Alta
-- UPDATE ATENDIMENTO.ALTA SET TIPOALTA = 'PB', DATA = '17-03-2018'
WHERE ID_Paciente = 15214

/* ALTERADO O TIPO DE ALTA PARA O PACIENTE MARIA LUIZA DE PAULA OLIVEIRA, A DATA JA ESTAVA CORRETA*/
SELECT * FROM Atendimento.Alta
-- UPDATE ATENDIMENTO.ALTA SET TIPOALTA = 'PE'
WHERE ID_Paciente = 15441


/* DELETADO A DUPLICIDADE DE ALTA PARA A PACIENTE MARIA APARECIDA REIS MOLINA*/
SELECT * FROM Atendimento.Alta
-- DELETE FROM Atendimento.Alta
WHERE ID = 11783

/* SEM REGISTRO DE ALTA PARA O PACIENTE GUARACI DE OLIVEIRA*/
SELECT * FROM Atendimento.Alta
-- DELETE FROM Atendimento.Alta
WHERE ID = 15373


/* ALTERA O TIPO DE ALTA DA PACIENTE ELISABETH FERREIRA DOS SANTOS*/
SELECT * FROM Atendimento.Alta
-- UPDATE ATENDIMENTO.ALTA SET TIPOALTA = 'PE'
WHERE ID_Paciente = 2666































