--SUBQUERYS
SELECT (SELECT 'DANILO') SUBCONSULTA;

SELECT 'DANILO' SUBCONSULTA;

--NÃO É POSSÍVEL AGRUPAR ESSA QUERY POR NOME, POIS TODAS AS COLUNAS DEVEM ESTAR NA CLAUSULA GROUP BY
USE RECEPCAO;
SELECT A.NomeEquipe, A.nome, A.idade, A.mae, A.CNS, B.DataFinaliza DataFinalização FROM INDICADORES.VW_PEP_SIAB A
INNER JOIN PEPMOVIMENTOS B ON A.IDPEP = B.CODPAC
INNER JOIN PEPMOVIMENTOS_CID C ON B.CODIGO = C.ID_PEPMOVIMENTOS
--GROUP BY A.NOME

--USANDO A SUBQUERY COM A QUERY DE CIMA - ESSA É UMA SUBQUERY COM TABELA DERIVADA
SELECT D.NomeEquipe, D.NOME, COUNT (D.NOME) QuantidadeDeAtendimentos  FROM 
(SELECT A.NomeEquipe, A.nome, A.idade, A.mae, A.CNS, B.DataFinaliza DataFinalização FROM INDICADORES.VW_PEP_SIAB A
INNER JOIN PEPMOVIMENTOS B ON A.IDPEP = B.CODPAC
INNER JOIN PEPMOVIMENTOS_CID C ON B.CODIGO = C.ID_PEPMOVIMENTOS) AS D
GROUP BY D.NOME, D.NomeEquipe