------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'FERNANDO FREDERICO OLIVEIRA' 

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'ELIETE LEITE DE OLIVEIRA'  
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'ALTAMIR LOPES MOREIRA' 

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'CAMILA TEREZA DE PAULA NEVES MOREIRA' 
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'ELIDA MARIA ASSIS DA SILVA'  
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'MESSIAS HESPANHOL BARBOSA'  
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'GUILHERME DA SILVA HESPANHOL BARBOSA'  
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'FRANCINEIDE CANDIDO DE OLIVEIRA'  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'SHEILA DE SOUZA AMARAL'  
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'RODRIGO DA SILVA BEZERRA ' 
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'BRUNA CELINE FONTES DA SILVA'  
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'JANAINA DE BRITO CELINE'  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'SUELENA MARTINS DA SILVA'  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'VERA LUCIA MARTINS DA SILVA'  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'ZILDA AYRES PRATA'  
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'BARBARA CABIDO PRATA'
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'CARLA GOMES PRATA'  
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME IN ('IRVIM GOMES PRATA',  
'ROSANE DE SOUZA DA GAMA TEIXEIRA',  
'INGRID GABRIELE ARAUJO BRITO',  
'JORGE DA GAMA TEIXEIRA',  
'JORGE DA GAMA TEIXEIRA JUNIOR',  
'ALLAN DE SOUZA GAMA TEIXEIRA',  
'DEUSA PEREIRA DE SOUZA GUIA',  
'JAIME PEREIRA GUIA', 
'ARLLON PEREIRA DE SOUZA GUIA',  
'CINTIA PEREIRA DE SOUZA GUIA',  
'ANDREIA MACEDO SANT ANNA') 

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME IN ('PAULO ROBERTO DE FARIA',  
'ZAMORA REIS RAMILO',  
'LUCY FERNANDES DA LUZ',  
'DILZA NOGUEIRA DA LUZ',    
'JOSE LUIZ FERREIRA DE CARVALHO',  
'GLEDSON LUIZ FERREIRA DE CARVALHO',  
'ELENITA DOS SANTOS SILVA',  
'TEOFILO TICAO DE CARVALHO',  
'DINORA SILVA MARTINS',  
'LUCENY MARTINS',  
'RICARDO DE SOUZA LAUD',  
'PEDRO HENRIQUE LAUD OLIVEIRA',  
'GLAUCIA CRISTINA LAUD',  
'CATHLEEN CRISTINA LAUD DE OLIVEIRA',  
'MARIA DAS GRACAS LAUD DE OLIVEIRA',  
'SOLANGE DE OLIVEIRA MENDONCA') 

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME IN ('ERIKA CRISTIANA NOGUEIRA PAPERA')

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME IN ('REGINA CELIA FERREIRA DE CARVALHO')  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME LIKE ('%LUIZ FERNANDO NASCIMENTO%')  
 



 




 
  



 
 
 
    
    


 
   
  
 