SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'ZILDA DEL GUIDICE DOS SANTOS'

--------------------------------------------

SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'AMANCIO SANTOS DE OLIVEIRA'

-------------------------------------------

SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'TANIA LUZIA LIMA VARELLA'

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'THALES LUAN LIMA VARELLA'  ,
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'CARLOS ARTUR GARCIA GOULART'  
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME like '%MARIA DAS GRACAS OLIVEIRA%'
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'CARINE DE OLIVEIRA GOULART'
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'MAISA SILVA DEL GUIDICE'

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'MAISA SILVA DEL GUIDICE'
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'EDUARDO DEL GUIDICE DOS SANTOS'  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'ELEN SILVA DEL GUIDICE'

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'MARIA DAS GRACAS LAURINDO TEODORO'

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'MARIA MEIRIA DE SA'

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'ANA PAULA DOS SANTOS NOGUEIRA' 

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'ANA MARIA MATTOS ALMEIDA'

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'ELIEZER RIBEIRO ALMEIDA'  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'DESIREE MATTOS ALMEIDA'  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'TAIS TORRES DE PAULA'  
 
------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'ANDRE FRANCISCO COELHO FILHO'

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'CARLOS ROBERTO BAPTISTA DA SILVA'  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'ELISA MARIA LEITE DE ASSIS DA SILVA' 

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'CARLOS GIL DE ASSIS'  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'RAFAELA BATISTA DO NASCIMENTO' 

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'CLEBER LUIZ DOS SANTOS'  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'LUANA DO NASCIMENTO ROCHA'  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'MARIA JOSE BATISTA NASCIMENTO'  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'TANIA REGINA LUIZ BORGES FERREIRA'  

------------------------------------------
SELECT * FROM SIABFACIL.PESSOA
-- UPDATE SIABFACIL.PESSOA SET FAMILIA_ID = NULL
WHERE NOME = 'VALERIA MENDES DE OLIVEIRA'  
 
 
 
 


 
 

 


  






