SELECT FA.COD_AREA, FA.MICROAREA, FA.NUMERO "FAMILIA", COUNT (PE.PLANO_DE_SAUDE_ID) "TOTAL PESSOAS COM PLANO" , PL.NOME "COBERTURA"
FROM SIABFACIL.FAMILIA FA
INNER JOIN SIABFACIL.PESSOA PE ON PE.FAMILIA_ID = FA.ID
INNER JOIN SIABFACIL.PLANO_DE_SAUDE PL ON PE.PLANO_DE_SAUDE_ID = PL.ID
WHERE PE.PLANO_DE_SAUDE_ID IS NOT NULL
AND FA.DATA_DESATIVACAO IS NULL
GROUP BY FA.COD_AREA, FA.MICROAREA, FA.NUMERO, PL.NOME
ORDER BY FA.COD_AREA, FA.MICROAREA, FA.NUMERO