SELECT * FROM (
select * from openquery(siab,'SELECT B.COD_AREA "EQUIPE", B.MICROAREA "MICRO",B.NUMERO "FAMILIA", A.NOME "NOME", A.CNS "CNS", A.NOME_DA_MAE "NOME DA MAE", 
TO_CHAR (A.DATA_NASCIMENTO, ''DD-MM-YYYY'') "DATA NASCIMENTO", D.DESCRICAO "LINHA DE CUIDADO" 
FROM SIABFACIL.PESSOA A
INNER JOIN SIABFACIL.FAMILIA B ON A.FAMILIA_ID = B.ID
INNER JOIN SIABFACIL.PESSOA_GRUPO_DE_PESSOAS C ON A.ID = C.PESSOA_ID
LEFT JOIN SIABFACIL.GRUPO_DE_PESSOAS D ON C.GRUPO_DE_PESSOAS_ID = D.ID
WHERE D.ID = 9 -- ACAMADO
AND A.DATA_DESATIVACAO IS NULL
AND A.FAMILIA_ID IS NOT NULL
AND B.DATA_DESATIVACAO IS NULL')
)AS TEMP




