USE RECEPCAO;

SET DATEFORMAT DMY	
SELECT * FROM (
SELECT  DISTINCT A.NOME, A.NOMEEQUIPE, A.IDADE, A.MAE, A.PRONTUARIO, A.CNS, CONVERT (VARCHAR (20), B.DATA, 103) DataResultado, convert(varchar(max),B.RESULTADO) resultado, convert(varchar(max),B.observacao) observacao
FROM INDICADORES.VW_PEP_SIAB A
INNER JOIN EXAMES.Colpocitologia B ON A.IDPEP = B.CODPAC
WHERE RESULTADO LIKE '%ALTO GRAU%'
OR RESULTADO LIKE '%ASC-US%'
OR RESULTADO LIKE '%ASC-H%'
OR RESULTADO LIKE '%AGC%'
OR RESULTADO LIKE '%BAIXO GRAU%'
OR RESULTADO LIKE '%LSIL%'
OR RESULTADO LIKE '%HSIL%'
OR RESULTADO LIKE '%LESAO%'
)QRY











