USE RECEPCAO;
SELECT C.NOMEEQUIPE, C.NOME 'NOME DO PACIENTE', b.nome 'NOME DO CONTATO', C.data_nascimento, c.mae  FROM PESSOA_GRUPO_DE_PESSOAS A
INNER JOIN tuberculose_contato B ON A.COD_PAC = B.ID_PACIENTE
INNER JOIN INDICADORES.VW_PEP_SIAB C ON A.COD_PAC = C.IDPEP
WHERE GRUPO_DE_PESSOAS_ID = 8
AND DATA_FINALIZACAO IS NULL


