/*CRIAR PROCEDIMENTO PARA INSERIR REGISTRO NA TABELA TELEFONETIPO*/

ALTER PROCEDURE TESTE --COMANDO PARA CRIAR A PROCEDURE
@IDTelefoneTipo INT, --PARAMETROS DOS CAMPOS QUE SERAO UTILIZADOS
@DescTelefoneTipo VARCHAR (30) = 'TESTE' --PARAMETRO DOS CAMPOS QUE SERAO UTILIZADOS, TESTE COLOQUEI COMO VALOR PADRAO
--SE AO CHAMAR ESSA PROCEDURE NÃO FOR PASSADO O PARÂMETROS DESCTELEFONETIPO O VALOR PADRAO PRA ESSE CAMPO SERA TESTE

AS
BEGIN --INICIO
INSERT INTO TelefoneTipo --COMANDO PARA INSERIR NA TABELA TELEFONETIPO
(
IDTelefoneTipo, --CAMPOS QUE FORAM DECLARADOS ACIMA E SERÃO UTILIZADOS NA INSERÇÃO DE DADOS
DescTelefoneTipo --CAMPOS QUE FORAM DECLARADOS ACIMA E SERÃO UTILIZADOS NA INSERÇÃO DE DADOS
) 

VALUES --VALORES

(
@IDTelefoneTipo, --PASSAR OS PARÂMETROS INFORMADOS ACIMA
@DescTelefoneTipo --PASSAR OS PARÂMETROS INFORMADOS ACIMA
)

END

EXEC Teste 4, 'CELULAR' --EXECUTAR A SP, INFORMAR OS VALORES DESEJADOS, NESSE CASO, 1 PARA IDTELEFONETIPO E RESIDENCIAL PARA DESCTELEFONETIPO

SELECT * FROM TelefoneTipo --SELECIONAR A TABELA TELEFONETIPO PARA VERIFICAR SE OS VALORES FORAM INSERIDOS 