USE recepcao;
SELECT DISTINCT D.NOMEEQUIPE, D.NOME, D.DATA_NASCIMENTO, MAE FROM PEPMOVIMENTOS_CID A
INNER JOIN PEPMOVIMENTOS B ON A.ID_PEPMOVIMENTOS = B.CODIGO
INNER JOIN CID C ON A.ID_CID = C.ID
INNER JOIN INDICADORES.VW_PEP_SIAB D ON B.CODPAC = D.IDPEP
WHERE C.CID10 = 'E10'




