SELECT * FROM (
SELECT AA.NOME, AA.NOMEEQUIPE, AA.IDADE, AA.MAE, AA.PRONTUARIO, AA.CNS, CONVERT (VARCHAR (20), BB.DATAFINALIZA, 103) DATAINSERCAO
FROM RECEPCAO.INDICADORES.VW_PEP_SIAB AA
INNER JOIN RECEPCAO.DBO.PEPMOVIMENTOS BB ON AA.IDPEP=BB.CODPAC
INNER JOIN RECEPCAO.DBO.PEPMOVIMENTOS_SOLI_PROCEDIMENTO CC ON BB.CODIGO=CC.ID_PEPMOVIMENTOS
INNER JOIN RECEPCAO.DBO.PROCEDIMENTOS DD ON CC.ID_EXAME=DD.ID
WHERE DD.CODPROC IN ('0301040028') 

UNION ALL

SELECT AA.NOME, AA.NOMEEQUIPE, AA.IDADE, AA.MAE, AA.PRONTUARIO, AA.CNS, CONVERT (VARCHAR (20), BB.DATAFINALIZA, 103) DATAINSERCAO
FROM   RECEPCAO.INDICADORES.VW_PEP_SIAB AA
INNER JOIN RECEPCAO.DBO.PEPMOVIMENTOS BB ON AA.IDPEP=BB.CODPAC
INNER JOIN RECEPCAO.DBO.PEPMOVIMENTOS_CID CC ON BB.CODIGO=CC.ID_PEPMOVIMENTOS
INNER JOIN RECEPCAO.DBO.CID DD ON CC.ID_CID=DD.ID
WHERE DD.CID10 IN ('Z301')

UNION ALL

SELECT AA.NOME, AA.NOMEEQUIPE, AA.IDADE, AA.MAE, AA.PRONTUARIO, AA.CNS, CONVERT (VARCHAR (20), CC.DATAFINALIZA, 103) DATAINSERCAO 
 FROM RECEPCAO.DBO.PEPMOVIMENTOS CC
INNER JOIN [DBO].[PEPMOVIMENTOS_SOLI_PROCEDIMENTO] BB ON BB.ID_PEPMOVIMENTOS = CC.CODIGO
INNER JOIN INDICADORES.VW_PEP_SIAB AA ON CC.CODPAC = AA.IDPEP
WHERE 
ID_EXAME =1068 AND CONVERT(VARCHAR(6), CC.DTATENDE, 112) =  CONVERT(VARCHAR(6), GETDATE(), 112)
) QRY