USE RECEPCAO;
SELECT  DISTINCT A.NOME, A.NOMEEQUIPE, A.IDADE, A.MAE, A.PRONTUARIO, A.CNS, D.NOME EXAME
FROM INDICADORES.VW_PEP_SIAB A INNER JOIN PEPMOVIMENTOS B ON A.IDPEP = B.CODPAC
INNER JOIN PepMovimentos_Soli_Exames C ON B.CODIGO = C.id_PepMovimentos
INNER JOIN PROCEDIMENTOS D ON C.ID_EXAME = D.ID
WHERE C.id_Exame = 4293










