/*Quantidade de Atendimentos Hipertensos Outubro 2016*/
USE RECEPCAO;
SELECT COUNT(*) AS QUANTIDADE_HIPERTENSOS_10_2016 FROM protocolo_hiperdia A
INNER JOIN PEPMOVIMENTOS B ON A.MOV_ID = B.CODIGO
INNER JOIN PACIENTES C ON B.CODPAC = C.CODIGO
INNER JOIN PESSOA_GRUPO_DE_PESSOAS D ON C.CODIGO = D.COD_PAC
WHERE B.DATAFINALIZA BETWEEN '2016-10-01 00:00:00.000'AND'2016-10-31 23:59:59.000'--Informar o período
AND D.ATIVO = 'S'
AND D.grupo_de_pessoas_id = 6--Hipertenso
AND B.STATUS = 'F'
AND C.CODIGO <>1

/*Quantidade de Atendimentos Hipertensos Novembro 2016*/
USE RECEPCAO;
SELECT COUNT(*) AS QUANTIDADE_HIPERTENSOS_11_2016 FROM protocolo_hiperdia A
INNER JOIN PEPMOVIMENTOS B ON A.MOV_ID = B.CODIGO
INNER JOIN PACIENTES C ON B.CODPAC = C.CODIGO
INNER JOIN PESSOA_GRUPO_DE_PESSOAS D ON C.CODIGO = D.COD_PAC
WHERE B.DATAFINALIZA BETWEEN '2016-11-01 00:00:00.000'AND'2016-11-30 23:59:59.000'--Informar o período
AND D.ATIVO = 'S'
AND D.grupo_de_pessoas_id = 6--Hipertenso
AND B.STATUS = 'F'
AND C.CODIGO <>1


/*Quantidade de Atendimentos Hipertensos Dezembro 2016*/
USE RECEPCAO;
SELECT COUNT(*) AS QUANTIDADE_HIPERTENSOS_12_2016 FROM protocolo_hiperdia A
INNER JOIN PEPMOVIMENTOS B ON A.MOV_ID = B.CODIGO
INNER JOIN PACIENTES C ON B.CODPAC = C.CODIGO
INNER JOIN PESSOA_GRUPO_DE_PESSOAS D ON C.CODIGO = D.COD_PAC
WHERE B.DATAFINALIZA BETWEEN '2016-12-01 00:00:00.000'AND'2016-12-31 23:59:59.000'--Informar o período
AND D.ATIVO = 'S'
AND D.grupo_de_pessoas_id = 6--Hipertenso
AND B.STATUS = 'F'
AND C.CODIGO <>1

/*Quantidade de Atendimentos Diabeticos Outubro 2016*/
USE RECEPCAO;
SELECT COUNT(*) AS QUANTIDADE_DIABETICOS_10_2016 FROM protocolo_hiperdia A
INNER JOIN PEPMOVIMENTOS B ON A.MOV_ID = B.CODIGO
INNER JOIN PACIENTES C ON B.CODPAC = C.CODIGO
INNER JOIN PESSOA_GRUPO_DE_PESSOAS D ON C.CODIGO = D.COD_PAC
WHERE B.DATAFINALIZA BETWEEN '2016-10-01 00:00:00.000'AND'2016-10-31 23:59:59.000'--Informar o período
AND D.ATIVO = 'S'
AND D.grupo_de_pessoas_id = 7--Diabeticos
AND B.STATUS = 'F'
AND C.CODIGO <>1


/*Quantidade de Atendimentos Diabeticos Novembro 2016*/
USE RECEPCAO;
SELECT COUNT(*) AS QUANTIDADE_DIABETICOS_11_2016 FROM protocolo_hiperdia A
INNER JOIN PEPMOVIMENTOS B ON A.MOV_ID = B.CODIGO
INNER JOIN PACIENTES C ON B.CODPAC = C.CODIGO
INNER JOIN PESSOA_GRUPO_DE_PESSOAS D ON C.CODIGO = D.COD_PAC
WHERE B.DATAFINALIZA BETWEEN '2016-11-01 00:00:00.000'AND'2016-11-30 23:59:59.000'--Informar o período
AND D.ATIVO = 'S'
AND D.grupo_de_pessoas_id = 7--Diabeticos
AND B.STATUS = 'F'
AND C.CODIGO <>1


/*Quantidade de Atendimentos Diabeticos Dezembro 2016*/
USE RECEPCAO;
SELECT COUNT(*) AS QUANTIDADE_DIABETICOS_12_2016 FROM protocolo_hiperdia A
INNER JOIN PEPMOVIMENTOS B ON A.MOV_ID = B.CODIGO
INNER JOIN PACIENTES C ON B.CODPAC = C.CODIGO
INNER JOIN PESSOA_GRUPO_DE_PESSOAS D ON C.CODIGO = D.COD_PAC
WHERE B.DATAFINALIZA BETWEEN '2016-12-01 00:00:00.000'AND'2016-12-31 23:59:59.000'--Informar o período
AND D.ATIVO = 'S'
AND D.grupo_de_pessoas_id = 7--Diabeticos
AND B.STATUS = 'F'
AND C.CODIGO <>1









