--CRIANÇAS DE 6 MESES A < 5 ANOS
USE RECEPCAO;
SELECT COUNT (DISTINCT IDSIAB) FROM INDICADORES.VW_PEP_SIAB
WHERE DATA_NASCIMENTO BETWEEN '2012-04-12' AND '2016-10-11'

--IDOSOS MAIORES DE 60 ANOS
SELECT COUNT (DISTINCT IDSIAB) FROM INDICADORES.VW_PEP_SIAB
WHERE IDADE > 60

--GESTANTES
SELECT COUNT (DISTINCT COD_PAC) FROM PESSOA_GRUPO_DE_PESSOAS
WHERE GRUPO_DE_PESSOAS_ID = 5
AND ATIVO = 'S'

--PUÉRPERAS
SELECT COUNT (DISTINCT COD_PAC) FROM PESSOA_GRUPO_DE_PESSOAS
WHERE GRUPO_DE_PESSOAS_ID = 5
AND ATIVO = 'N'
AND DATA_FINALIZACAO > '2017-02-25 00:33:20.540'


