USE RECEPCAO
GO

IF object_id(N'siabfacil.vw_ficha_deficiente', 'V') IS NOT NULL
	DROP VIEW siabfacil.vw_ficha_deficiente
GO

create view siabfacil.vw_ficha_deficiente
as
(
	select * from openquery(siab,'SELECT * FROM SIABFACIL.VW_DEFICIENTE') -- VIEW NO SIAB
)
GO


--------------


IF object_id(N'siabfacil.vw_ficha_b_tuberculose', 'V') IS NOT NULL
	DROP VIEW siabfacil.vw_ficha_b_tuberculose
GO

create view siabfacil.vw_ficha_b_tuberculose
as
(
	select * from openquery(siab,'
		SELECT DISTINCT PE.ID IDSiab, (SELECT CC.CD_SEGMENTO 
				  FROM SIABFACIL.FAMILIA FA 
				  JOIN CNES.LFCES041 BB ON BB.COD_AREA = FA.COD_AREA 
				  JOIN CNES.LFCES040 CC ON CC.CD_SEGMENTO = BB.SEG
				  LIMIT 1) "AP",
			(SELECT CNES FROM CNES.LFCES004) "CNES_UNIDADE", 
			(SELECT NOME_FANTA FROM CNES.LFCES004) "NOME_UNIDADE",
			A.COD_AREA "EQUIPE",
			FA.MICROAREA "MICRO",
			PE.NOME "NOME",
			TO_CHAR(PE.DATA_NASCIMENTO, ''DD/MM/YYYY'') "NASCIMENTO",
			EXTRACT (YEAR FROM AGE(CURRENT_DATE, PE.DATA_NASCIMENTO)) "IDADE",
			PE.CNS "CNS",
			CASE WHEN PE.SEXO = TRUE THEN ''M'' ELSE ''F'' END "SEXO",
			FA.COD_AREA || ''.'' || FA.MICROAREA || ''.'' || FA.NUMERO "PRONTUARIO",
			OC.DESCRICAO "OCUPACAO",
			CASE WHEN TB.MEDICACAO_DIARIA = TRUE THEN ''SIM'' ELSE ''NAO'' END "USA_MEDICACAO_DIARIA",
			CASE WHEN TB.REACOES = TRUE THEN ''SIM'' ELSE ''NAO'' END "REACOES_INDESEJAVEIS",
			CASE WHEN TB.EXAME_ESCARRO = TRUE THEN ''SIM'' ELSE ''NAO'' END "EXAME_ESCARRO",
			TO_CHAR (TB.ULTIMA_CONSULTA, ''DD/MM/YYYY'') "DATA_ULTIMA_CONSULTA",
			TB.OBS "OBSERVA합ES",
		TO_CHAR (TB.DATA_VISITA, ''DD/MM/YYYY'') "VISITA_DO_ACS"
			FROM SIABFACIL.PESSOA PE
		INNER JOIN SIABFACIL.FAMILIA FA ON PE.FAMILIA_ID = FA.ID
		INNER JOIN SIABFACIL.OCUPACAO OC ON OC.ID = PE.OCUPACAO_ID
		INNER JOIN SIABFACIL.SIAB_B_TB TB ON PE.ID = PERSON_ID
		INNER JOIN SIABFACIL.PESSOA_GRUPO_DE_PESSOAS PGP ON  PE.ID = PGP.PESSOA_ID
		INNER JOIN SIABFACIL.GRUPO_DE_PESSOAS GP ON PGP.GRUPO_DE_PESSOAS_ID = GP.ID
		INNER JOIN SIABFACIL.PESSOA_GRUPO_DE_PESSOAS_LOG GPL ON PE.ID = GPL.PESSOA_ID
		INNER JOIN CNES.LFCES038 A ON FA.PROF_ID = A.PROF_ID
		INNER JOIN CNES.LFCES018 B ON A.PROF_ID = B.PROF_ID
		WHERE PGP.GRUPO_DE_PESSOAS_ID = 8 -- TUBERCULOSE
		--AND EXTRACT (YEAR FROM TB.ULTIMA_CONSULTA) = 2016
		AND GPL.DATA_SAIDA IS NULL
		AND PE.DATA_DESATIVACAO IS NULL
		AND FA.DATA_DESATIVACAO IS NULL
			GROUP BY PE.ID, A.COD_AREA, FA.COD_AREA, FA.MICROAREA, PE.NOME, PE, PE.CNS, PE.SEXO, PE.DATA_NASCIMENTO, FA.NUMERO, OC.DESCRICAO,
			TB.MEDICACAO_DIARIA, TB.REACOES, TB.EXAME_ESCARRO, TB.ULTIMA_CONSULTA, TB.OBS, TB.DATA_VISITA
			ORDER BY A.COD_AREA, FA.MICROAREA
	')
)
go


-------------------------


IF object_id(N'siabfacil.vw_ficha_b_hipertenso', 'V') IS NOT NULL
	DROP VIEW siabfacil.vw_ficha_b_hipertenso
GO

create view siabfacil.vw_ficha_b_hipertenso
as
(
	select * from openquery(siab,'
		SELECT DISTINCT PE.ID IDSiab, (SELECT CC.CD_SEGMENTO 
		  FROM SIABFACIL.FAMILIA FA 
		  JOIN CNES.LFCES041 BB ON BB.COD_AREA = FA.COD_AREA 
		  JOIN CNES.LFCES040 CC ON CC.CD_SEGMENTO = BB.SEG
		  LIMIT 1) "AP",
		(SELECT CNES FROM CNES.LFCES004) "NUMERO CNES_UNIDADE", 
		(SELECT NOME_FANTA FROM CNES.LFCES004) "NOME_UNIDADE",
		A.COD_AREA "EQUIPE",
		FA.MICROAREA "MICRO",
		PE.NOME "NOME",
		TO_CHAR(PE.DATA_NASCIMENTO, ''DD/MM/YYYY'') "NASCIMENTO",
		EXTRACT (YEAR FROM AGE(CURRENT_DATE, PE.DATA_NASCIMENTO)) "IDADE",
		PE.CNS "CNS",
		CASE WHEN PE.SEXO = TRUE THEN ''M'' ELSE ''F'' END "SEXO",
		FA.COD_AREA || ''.'' || FA.MICROAREA || ''.'' || FA.NUMERO "PRONTUARIO",
		OC.DESCRICAO "OCUPACAO",
		CASE WHEN HA.MEDICACAO = TRUE THEN ''SIM'' ELSE ''NAO'' END "USA_MEDICACAO_DIARIA",
		CASE WHEN HA.DIETA = TRUE THEN ''SIM'' ELSE ''NAO'' END "FAZ_DIETA",
		CASE WHEN HA.EXERCICIOS = TRUE THEN ''SIM'' ELSE ''NAO'' END "FAZ_EXERCICIOS",
		HA.PRESSAO_MINIMA || ''x'' || HA.PRESSAO_MINIMA "PRESSAO",
		TO_CHAR (HA.ULTIMA_CONSULTA, ''DD/MM/YYYY'') "DATA_ULTIMA_CONSULTA",
		HA.OBS "OBSERVACOES",
		TO_CHAR (HA.DATA_VISITA, ''DD/MM/YYYY'') "VISITA_DO_ACS"
		FROM SIABFACIL.PESSOA PE
	INNER JOIN SIABFACIL.FAMILIA FA ON PE.FAMILIA_ID = FA.ID
	INNER JOIN SIABFACIL.OCUPACAO OC ON OC.ID = PE.OCUPACAO_ID
	INNER JOIN SIABFACIL.SIAB_B_HA HA ON PE.ID = PERSON_ID
	INNER JOIN SIABFACIL.PESSOA_GRUPO_DE_PESSOAS PGP ON  PE.ID = PGP.PESSOA_ID
	INNER JOIN SIABFACIL.GRUPO_DE_PESSOAS GP ON PGP.GRUPO_DE_PESSOAS_ID = GP.ID
	INNER JOIN SIABFACIL.PESSOA_GRUPO_DE_PESSOAS_LOG GPL ON PE.ID = GPL.PESSOA_ID
	INNER JOIN CNES.LFCES038 A ON FA.PROF_ID = A.PROF_ID
	INNER JOIN CNES.LFCES018 B ON A.PROF_ID = B.PROF_ID
	WHERE PGP.GRUPO_DE_PESSOAS_ID = 6 -- HIPERTENSO
	--AND EXTRACT (YEAR FROM HA.ULTIMA_CONSULTA) = 2016
	AND GPL.DATA_SAIDA IS NULL
	AND PE.DATA_DESATIVACAO IS NULL
	AND FA.DATA_DESATIVACAO IS NULL
		GROUP BY PE.ID, A.COD_AREA, FA.COD_AREA, FA.MICROAREA, PE.NOME, PE, PE.CNS, PE.SEXO, PE.DATA_NASCIMENTO, FA.NUMERO, OC.DESCRICAO,
		HA.MEDICACAO, HA.DIETA, HA.EXERCICIOS, HA.PRESSAO_MINIMA, HA.ULTIMA_CONSULTA, HA.OBS, HA.DATA_VISITA
		ORDER BY A.COD_AREA, FA.MICROAREA


	')
)
go


----------------------------


IF object_id(N'siabfacil.vw_ficha_b_hanseniase', 'V') IS NOT NULL
	DROP VIEW siabfacil.vw_ficha_b_hanseniase
GO

create view siabfacil.vw_ficha_b_hanseniase
as
(
	select * from openquery(siab,'
		SELECT DISTINCT PE.ID IDSiab, (SELECT CC.CD_SEGMENTO 
			  FROM SIABFACIL.FAMILIA FA 
			  JOIN CNES.LFCES041 BB ON BB.COD_AREA = FA.COD_AREA 
			  JOIN CNES.LFCES040 CC ON CC.CD_SEGMENTO = BB.SEG
			  LIMIT 1) "AP",
		(SELECT CNES FROM CNES.LFCES004) "NUMERO_CNES", 
		(SELECT NOME_FANTA FROM CNES.LFCES004) "NOME_UNIDADE",
		--DADOS DA UNIDADE E ACS
		A.COD_AREA "EQUIPE",
		FA.MICROAREA "MICRO",
		PE.NOME "NOME",
		TO_CHAR(PE.DATA_NASCIMENTO, ''DD/MM/YYYY'') "NASCIMENTO",
		EXTRACT (YEAR FROM AGE(CURRENT_DATE, PE.DATA_NASCIMENTO)) "IDADE",
		PE.CNS "CNS",
		CASE WHEN PE.SEXO = TRUE THEN ''M'' ELSE ''F'' END "SEXO",
		FA.COD_AREA || ''.'' || FA.MICROAREA || ''.'' || FA.NUMERO "PRONTUARIO",
		OC.DESCRICAO "OCUPACAO",
		CASE WHEN HAN.MEDICACAO_DIARIA = TRUE THEN ''SIM'' ELSE ''NAO'' END "USA_MEDICACAO_DIARIA",
		HAN.DATA_ULTIMA_DOSE_SUPERVISIONADA "DATA_ULTIMA_DOSE_SUPERVISIONADA",
		CASE WHEN HAN.AUTO_CUIDADO = TRUE THEN ''SIM'' ELSE ''NAO'' END "AUTO_CUIDADO",
		CASE WHEN HAN.EXAMINADO = TRUE THEN ''SIM'' ELSE ''NAO'' END "EXAMINADO",
		CASE WHEN HAN.BCG = TRUE THEN ''SIM'' ELSE ''NAO'' END "BCG",
		TO_CHAR (HAN.ULTIMA_CONSULTA, ''DD/MM/YYYY'') "DATA_ULTIMA_CONSULTA",
		HAN.OBS "OBSERVA합ES",
		TO_CHAR (HAN.DATA_VISITA, ''DD/MM/YYYY'') "VISITA_DO_ACS"
		FROM SIABFACIL.PESSOA PE
	INNER JOIN SIABFACIL.FAMILIA FA ON PE.FAMILIA_ID = FA.ID
	INNER JOIN SIABFACIL.OCUPACAO OC ON OC.ID = PE.OCUPACAO_ID
	INNER JOIN SIABFACIL.SIAB_B_HAN HAN ON PE.ID = HAN.PESSOA_ID
	INNER JOIN SIABFACIL.PESSOA_GRUPO_DE_PESSOAS PGP ON  PE.ID = PGP.PESSOA_ID
	INNER JOIN SIABFACIL.GRUPO_DE_PESSOAS GP ON PGP.GRUPO_DE_PESSOAS_ID = GP.ID
	INNER JOIN SIABFACIL.PESSOA_GRUPO_DE_PESSOAS_LOG GPL ON PE.ID = GPL.PESSOA_ID
	INNER JOIN CNES.LFCES038 A ON FA.PROF_ID = A.PROF_ID
	INNER JOIN CNES.LFCES018 B ON A.PROF_ID = B.PROF_ID
	WHERE PGP.GRUPO_DE_PESSOAS_ID = 3 -- HANSENIASE
	--AND EXTRACT (YEAR FROM HAN.ULTIMA_CONSULTA) = 2016
	AND GPL.DATA_SAIDA IS NULL
	AND PE.DATA_DESATIVACAO IS NULL
	AND FA.DATA_DESATIVACAO IS NULL
		GROUP BY PE.ID, A.COD_AREA, FA.COD_AREA, FA.MICROAREA, PE.NOME, PE, PE.CNS, PE.SEXO, PE.DATA_NASCIMENTO, FA.NUMERO, OC.DESCRICAO,
		HAN.MEDICACAO_DIARIA, HAN.DATA_ULTIMA_DOSE_SUPERVISIONADA, HAN.AUTO_CUIDADO, HAN.EXAMINADO, HAN.BCG, HAN.ULTIMA_CONSULTA,
		HAN.OBS, HAN.DATA_VISITA
		ORDER BY A.COD_AREA, FA.MICROAREA
	')
)
go


-----------------------------


IF object_id(N'siabfacil.vw_ficha_b_diabetico', 'V') IS NOT NULL
	DROP VIEW siabfacil.vw_ficha_b_diabetico
GO

create view siabfacil.vw_ficha_b_diabetico
as
(
	select * from openquery(siab,'
		SELECT DISTINCT PE.ID IDSiab, (SELECT CC.CD_SEGMENTO 
			  FROM SIABFACIL.FAMILIA FA 
			  JOIN CNES.LFCES041 BB ON BB.COD_AREA = FA.COD_AREA 
			  JOIN CNES.LFCES040 CC ON CC.CD_SEGMENTO = BB.SEG
			  LIMIT 1) "AP",
		(SELECT CNES FROM CNES.LFCES004) "NUMERO_CNES", 
		(SELECT NOME_FANTA FROM CNES.LFCES004) "NOME_UNIDADE",
		A.COD_AREA "EQUIPE",
		FA.MICROAREA "MICRO",
		PE.NOME "NOME",
		TO_CHAR(PE.DATA_NASCIMENTO, ''DD/MM/YYYY'') "NASCIMENTO",
		EXTRACT (YEAR FROM AGE(CURRENT_DATE, PE.DATA_NASCIMENTO)) "IDADE",
		PE.CNS "CNS",
		CASE WHEN PE.SEXO = TRUE THEN ''M'' ELSE ''F'' END "SEXO",
		FA.COD_AREA || ''.'' || FA.MICROAREA || ''.'' || FA.NUMERO PRONTUARIO,
		OC.DESCRICAO "OCUPACAO",
		CASE WHEN DIA.DIETA = TRUE THEN ''SIM'' ELSE ''NAO'' END "FAZ_DIETA",
		CASE WHEN DIA.INSULINA = TRUE THEN ''SIM'' ELSE ''NAO'' END "USA_INSULINA",
		CASE WHEN DIA.EXERCICIOS = TRUE THEN ''SIM'' ELSE ''NAO'' END "FAZ_EXERCICIOS",
		CASE WHEN DIA.HIPOGLICEMIANTE_ORAL = TRUE THEN ''SIM'' ELSE ''NAO'' END "HIPOGLICEMIA_ORAL",
		CASE WHEN DIA.PE_DIABETICO = TRUE THEN ''SIM'' ELSE ''NAO'' END "POSSUI_PE_DIABETICO",
		CASE WHEN DIA.AMPUTACAO = TRUE THEN ''SIM'' ELSE ''NAO'' END "POSSUI_AMPUTACAO",
		TO_CHAR (DIA.ULTIMA_CONSULTA, ''DD/MM/YYYY'') "ULTIMA_CONSULTA",
		TO_CHAR (DIA.DATA_VISITA, ''DD/MM/YYYY'') "VISITA_DO_ACS",
		DIA.OBS "OBSERVACOES"
	FROM SIABFACIL.PESSOA PE
	INNER JOIN SIABFACIL.FAMILIA FA ON PE.FAMILIA_ID = FA.ID
	INNER JOIN SIABFACIL.OCUPACAO OC ON OC.ID = PE.OCUPACAO_ID
	INNER JOIN SIABFACIL.SIAB_B_DIA DIA ON PE.ID = PERSON_ID
	INNER JOIN SIABFACIL.PESSOA_GRUPO_DE_PESSOAS PGP ON  PE.ID = PGP.PESSOA_ID
	INNER JOIN SIABFACIL.GRUPO_DE_PESSOAS GP ON PGP.GRUPO_DE_PESSOAS_ID = GP.ID
	INNER JOIN SIABFACIL.PESSOA_GRUPO_DE_PESSOAS_LOG GPL ON PE.ID = GPL.PESSOA_ID
	INNER JOIN CNES.LFCES038 A ON FA.PROF_ID = A.PROF_ID
	INNER JOIN CNES.LFCES018 B ON A.PROF_ID = B.PROF_ID
	WHERE PGP.GRUPO_DE_PESSOAS_ID = 7 -- DIABETICO
	--AND EXTRACT (YEAR FROM DIA.ULTIMA_CONSULTA) = 2016
	AND GPL.DATA_SAIDA IS NULL
	AND PE.DATA_DESATIVACAO IS NULL
	AND FA.DATA_DESATIVACAO IS NULL
		GROUP BY PE.ID, A.COD_AREA, FA.COD_AREA, FA.MICROAREA, PE.NOME, PE, PE.CNS, PE.SEXO, PE.DATA_NASCIMENTO, FA.NUMERO, OC.DESCRICAO, DIA.DIETA,
		DIA.INSULINA, DIA.EXERCICIOS, DIA.HIPOGLICEMIANTE_ORAL, DIA.PE_DIABETICO, DIA.AMPUTACAO, DIA.OBS, DIA.ULTIMA_CONSULTA, DIA.DATA_VISITA
		ORDER BY A.COD_AREA, FA.MICROAREA

	')
)
go


----------------------------------


IF object_id(N'siabfacil.vw_ficha_c_crianca', 'V') IS NOT NULL
	DROP VIEW siabfacil.vw_ficha_c_crianca
GO

create view siabfacil.vw_ficha_c_crianca
as
(
	select * from openquery(siab,'
		SELECT DISTINCT PE.ID IDSiab, (SELECT CC.CD_SEGMENTO 
			  FROM SIABFACIL.FAMILIA FA 
			  JOIN CNES.LFCES041 BB ON BB.COD_AREA = FA.COD_AREA 
			  JOIN CNES.LFCES040 CC ON CC.CD_SEGMENTO = BB.SEG
			  LIMIT 1) "AP",
		(SELECT CNES FROM CNES.LFCES004) "NUMERO_CNES", 
		(SELECT NOME_FANTA FROM CNES.LFCES004) "NOME_UNIDADE",
		PE.NOME "NOME",
		TO_CHAR(PE.DATA_NASCIMENTO, ''DD/MM/YYYY'') "NASCIMENTO",
		AGE(PE.DATA_NASCIMENTO) "IDADE",
		PE.CNS "CNS",
		CASE WHEN PE.SEXO = TRUE THEN ''M'' ELSE ''F'' END "SEXO",
		FA.COD_AREA || ''.'' || FA.MICROAREA || ''.'' || FA.NUMERO "PRONTUARIO",
		CASE WHEN FC.LOCAL_ACOMPANHAMENTO_ESF = TRUE THEN ''SIM'' ELSE ''NAO'' END "ACOMPANHADO_EM_ESF",
		CASE WHEN FC.LOCAL_ACOMPANHAMENTO_CONVENIO = TRUE THEN ''SIM'' ELSE ''NAO'' END "ACOMPANHADO_EM_CONVENIO",
		CASE WHEN FC.LOCAL_ACOMPANHAMENTO_OUTROS = TRUE THEN ''SIM'' ELSE ''NAO'' END "ACOMPANHADO_EM_OUTROS",
		FC.PESO "PESO_KG",
		CASE FC.OBS_PESO
		WHEN ''P'' THEN ''PESADO''
		WHEN ''NP'' THEN ''NAO PESADO''
		WHEN ''NI'' THEN ''NAO INFORMADO'' END "OBS_PESO",
 		FC.ALTURA "ALTURA_CM",
		CASE FC.OBS_ALTURA
		WHEN ''M'' THEN ''MEDIDO''
		WHEN ''NM'' THEN ''NAO MEDIDO''
		WHEN ''NI'' THEN ''NAO INFORMADO'' END "OBS_ALTURA",
		CASE WHEN FC.CONSULTA_MED = TRUE THEN ''SIM'' ELSE ''NAO'' END "CONSULTA_MEDICA",
		CASE WHEN FC.CONSULTA_ENF = TRUE THEN ''SIM'' ELSE ''NAO'' END "CONSULTA_ENFERMAGEM",
		CASE WHEN FC.CONSULTA_FALTOU = TRUE THEN ''SIM'' ELSE ''NAO'' END "FALTA_EM_CONSULTA",
		CASE WHEN FC.CONSULTA_NAO_INFORMADO = TRUE THEN ''SIM'' ELSE ''NAO'' END "NAO_INFORMADO",
		CASE WHEN FC.CONSULTA_NAO_AGENDOU = FALSE THEN ''NAO AGENDADO'' END "NAO_AGENDOU_CONSULTA",
		FC.CONSULTA_MOTIVO_FALTA "MOTIVO_DA_FALTA_EM_CONSULTA",
		CASE WHEN FC.ATENDIMENTO_ODONTOLOGICO_MES = TRUE THEN ''SIM'' ELSE ''NAO'' END "ATENDIMENTO_ODONTOLOGICO_NO_MES",
		CASE WHEN FC.GRUPO_EDUCATIVO_MES = TRUE THEN ''SIM'' ELSE ''NAO'' END "GRUPO_EDUCATIVO_NO_MES",
		CASE WHEN FC.PRONTO_SOCORRO_MES = TRUE THEN ''SIM'' ELSE ''NAO'' END "CONSULTA_NO_MES",
		CASE WHEN FC.VACINA_EM_DIA = TRUE THEN ''SIM'' ELSE ''NAO'' END "VACINA_EM_DIA",
		CASE WHEN FC.DESNUTRIDO = TRUE THEN ''SIM'' ELSE ''NAO'' END "DESNUTRIDO",
		CASE WHEN FC.OBESO = TRUE THEN ''SIM'' ELSE ''NAO'' END "OBESO",
		CASE WHEN FC.DIARREIA = TRUE THEN ''SIM'' ELSE ''NAO'' END "DIARREIA",
		CASE WHEN FC.DIARREIA_TRO = TRUE THEN ''SIM'' ELSE ''NAO'' END "DIARREIA_TRO",
		CASE WHEN FC.IRA = TRUE THEN ''SIM'' ELSE ''NAO'' END "IRA",
		CASE WHEN FC.ANTIBIOTICO = TRUE THEN ''SIM'' ELSE ''NAO'' END "TOMA_ANTIBIOTICO",
		CASE WHEN FC.HOSPITALIZACAO = TRUE THEN ''SIM'' ELSE ''NAO'' END "HOSPITALIZA플O",
		CASE WHEN FC.ACIDENTE_INFANCIA = TRUE THEN ''SIM'' ELSE ''NAO'' END "TEVE_ACIDENTE_NA_INFANCIA",
		TA.DESCRICAO "TIPO_DE_ACIDENTE",
		CASE WHEN FC.FREQUENTA_CRECHE = TRUE THEN ''SIM'' ELSE ''NAO'' END "FREQUENTA_CRECHE",
		CS.NOME "NOME_DA_CRECHE",
		FC.OUTRA_DOENCA "OUTRA_DOENCA",
		FC.OBS "OBSERVA합ES",
		TO_CHAR (FC.DATA_VISITA, ''DD/MM/YYYY'') "VISITA_DO_ACS"
	FROM SIABFACIL.ATENDIMENTO AT 
	INNER JOIN SIABFACIL.PESSOA PE ON AT.PESSOA_ID = PE.ID
	INNER JOIN SIABFACIL.FAMILIA FA ON (PE.FAMILIA_ID = FA.ID) AND (FA.PROF_ID IS NOT NULL)
	INNER JOIN SIABFACIL.SIAB_C FC ON PE.ID = FC.PESSOA_ID
	LEFT JOIN SIABFACIL.CRECHE_ESCOLA CS ON FC.CRECHE_ESCOLA_ID = CS.ID
	LEFT JOIN SIABFACIL.TIPO_ACIDENTE TA ON FC.TIPO_ACIDENTE_ID = TA.ID
	WHERE AT.MONITORADOR_ID = 3 
	AND AT.EXCLUIDO = FALSE 
		GROUP BY PE.ID, PE.NOME, PE.DATA_NASCIMENTO, PE.CNS, PE.SEXO, FA.COD_AREA, FC.PESO, FA.MICROAREA, FA.NUMERO, FC.ALTURA, FC.ATENDIMENTO_ODONTOLOGICO_MES, FC.GRUPO_EDUCATIVO_MES,
			 FC.PRONTO_SOCORRO_MES, FC.VACINA_EM_DIA, FC.DESNUTRIDO, FC.OBESO, FC.DIARREIA, FC.DIARREIA_TRO, FC.IRA, FC.ANTIBIOTICO, FC.HOSPITALIZACAO, FC.ACIDENTE_INFANCIA,
			 FC.FREQUENTA_CRECHE, CS.NOME, FC.OUTRA_DOENCA, FC.CONSULTA_MED, FC.CONSULTA_ENF, FC.CONSULTA_FALTOU, FC.CONSULTA_NAO_INFORMADO, FC.LOCAL_ACOMPANHAMENTO_ESF,
			 FC.LOCAL_ACOMPANHAMENTO_CONVENIO, FC.LOCAL_ACOMPANHAMENTO_OUTROS, FC.OBS_PESO, FC.OBS_ALTURA, FC.CONSULTA_NAO_AGENDOU, FC.CONSULTA_MOTIVO_FALTA, TA.DESCRICAO, TA.ID,
			 FC.OBS, FC.DATA_VISITA
	HAVING DATE_PART(''YEAR'',AGE(PE.DATA_NASCIMENTO)) < 2
	ORDER BY PE.NOME

	')
)
go



--------------------------------------


IF object_id(N'siabfacil.vw_ficha_gestante', 'V') IS NOT NULL
	DROP VIEW siabfacil.vw_ficha_gestante
GO

create view siabfacil.vw_ficha_gestante
as
(
		select * from openquery(siab,'
			select * from siabfacil.vw_gestante
	')
)
go

-----------------------------------


IF object_id(N'siabfacil.vw_ficha_A_individual', 'V') IS NOT NULL
	DROP VIEW siabfacil.vw_ficha_A_individual
GO

create view siabfacil.vw_ficha_A_individual
as
(
	select * from openquery(siab,'
		SELECT DISTINCT PP.ID IDSiab, (SELECT CC.CD_SEGMENTO 
		  FROM SIABFACIL.FAMILIA FA 
		  JOIN CNES.LFCES041 BB ON BB.COD_AREA = FA.COD_AREA 
		  JOIN CNES.LFCES040 CC ON CC.CD_SEGMENTO = BB.SEG
		  LIMIT 1) "AP",
		(SELECT CNES FROM CNES.LFCES004) "NUMERO_CNES_UNIDADE",
		B.CO_EQUIPE "INE_EQUIPE",
		(SELECT NOME_FANTA FROM CNES.LFCES004) "NOME_UNIDADE",
		B.NM_REFERENCIA "NOME_EQUIPE",
		A.COD_CNS "CNS_PROFIS",
		A.NOME_PROF "NOME_ACS",
		TO_CHAR(PP.DATA_ATIVACAO, ''DD/MM/YYYY'') "DATA_CADASTRO",
		FA.COD_AREA || ''.'' || FA.MICROAREA || ''.'' || FA.NUMERO "PRONTUARIO",
		PP.CNS "CNS_PAC",
		PP.NOME "NOME_DA_PESSOA",
		PP.APELIDO "NOME_SOCIAL",
		TO_CHAR (PP.DATA_NASCIMENTO, ''DD/MM/YYYY'') "DATA_DE_NACIMENTO",
		CASE WHEN PP.SEXO = TRUE THEN ''M'' ELSE ''F'' END "SEXO",
		PF.DESCRICAO "RELACAO_DE_PARENTESCO_COM_REPRESENTANTE",
		C.DS_RACA "RACA_COR",
		PP.NIS "NIS",
		PP.NOME_DA_MAE "MAE",
		CASE PP.MAE_DESCONHECIDA 
		WHEN TRUE THEN ''SIM''
		WHEN FALSE THEN ''NAO'' ELSE ''NAO_INFORMADO'' END "MAE_DESCONHECIDA",
		CASE WHEN NA.DESCRICAO IS NULL THEN ''NAO_INFORMADO'' ELSE NA.DESCRICAO END "NACIONALIDADE",
		E.DS_PAIS "PAIS",
		PP.TELEFONE "CELULAR",
		PP.TELEFONE_2 "CONTATO_TEL_2",
		PP.TELEFONE_3 "CONTATO_TEL_3",
		PP.EMAIL "EMAIL",
		D.NOME_MUN "MUNICIPIO",
		CASE WHEN EC.DESCRICAO IS NULL THEN ''NAO_INFORMADO'' ELSE EC.DESCRICAO END "ESTADO_CIVIL",
		CASE WHEN OC.DESCRICAO IS NULL THEN ''NAO_INFORMADO'' ELSE OC.DESCRICAO END "PROFISSAO",
		CASE WHEN PP.FREQUENTA_ESCOLA = TRUE THEN ''SIM'' ELSE ''NAO'' END "FRENQUENTA_ESCOLA",
		CASE WHEN ES.DESCRICAO IS NULL THEN ''NAO_INFORMADO'' ELSE ES.DESCRICAO END "ESCOLADIDADE",
		CASE WHEN TR.ID IS NULL THEN ''NAO_INFORMADO'' ELSE ST.DESCRICAO END "SITUACAO_DE_TRABALHO",
		CASE WHEN RC.DESCRICAO IS NULL THEN ''NAO_INFORMADO'' ELSE RC.DESCRICAO END "CRIANCAS_DE_0_A_9_ANOS_COM_QUEM_FICA",
		CASE WHEN PP.FREQUENTA_BENZEDEIRA = TRUE THEN ''SIM'' ELSE ''NAO'' END "FREQUENTA_BEZENDEIRA_CURANDEIRA",
		CASE WHEN PP.GRUPO_COMUNITARIO = TRUE THEN ''SIM'' ELSE ''NAO'' END "PARTICIPA_DE_GRUPO_COMUNITARIO",
		CASE WHEN PS.NOME IS NULL THEN ''NAO_INFORMADO'' ELSE PS.NOME END "POSSUI_PLANO_DE_SAUDE",
		CASE WHEN PP.POVO_COMUNIDADE_TRADICIONAL IS NULL THEN ''NAO_INFORMADO'' ELSE PP.POVO_COMUNIDADE_TRADICIONAL END "E_MEMBRO_DE_POVO_OU_COMUNIDADE_TRADICIONAL",
		CASE WHEN OS.DESCRICAO IS NULL THEN ''NAO_INFORMADO'' ELSE OS.DESCRICAO END "ORIENTACAO_SEXUAL",
		CASE WHEN GP.DESCRICAO IS NULL THEN ''NAO_INFORMADO'' ELSE GP.DESCRICAO END "LINHA_DE_CUIDADO",
		PP.MATERNIDADE_REFERENCIA "MATERNIDADE_DE_REFERENCIA_GEST",
		CASE PP.DEF_FISICA
		WHEN TRUE THEN ''SIM''
		WHEN FALSE THEN ''NAO'' ELSE ''NAO_INFORMADO'' END "DEFICIENCIA_FISICA",
		CASE PP.DEF_MENTAL
		WHEN TRUE THEN ''SIM''
		WHEN FALSE THEN ''NAO'' ELSE ''NAO_INFORMADO'' END "DEFICIENCIA_MENTAL",
		CASE PP.DEF_VISUAL
		WHEN TRUE THEN ''SIM''
		WHEN FALSE THEN ''NAO'' ELSE ''NAO_INFORMADO'' END "DEFICIENCIA_VISUAL",
		CASE PP.DEF_AUDITIVA
		WHEN TRUE THEN ''SIM''
		WHEN FALSE THEN ''NAO'' ELSE ''NAO_INFORMADO'' END "DEFICIENCIA_AUDITIVA",
		CASE PP.AVC_DERRAME 
		WHEN TRUE THEN ''SIM'' 
		WHEN FALSE THEN ''NAO'' ELSE ''NAO_INFORMADO'' END "TEVE_AVC_DERRAME",
		CASE PP.INFARTO 
		WHEN TRUE THEN ''SIM'' 
		WHEN FALSE THEN ''NAO'' ELSE ''NAO_INFORMADO'' END "TEVE_INFARTO",
		CASE WHEN RE.DESCRICAO IS NULL THEN ''NAO_INFORMADO'' ELSE RE.DESCRICAO END "DOENCA_RESPIRATORIA",
		CASE WHEN DC.DESCRICAO IS NULL THEN ''NAO_INFORMADO'' ELSE DC.DESCRICAO END "DOENCA_CARDIACA",
		CASE PP.TEM_TEVE_CANCER 
		WHEN TRUE THEN ''SIM'' 
		WHEN FALSE THEN ''NAO'' ELSE ''NAO INFORMADO'' END "TEM_OU_TEVE_CANCER",
		TC.DESCRICAO "TIPO_DE_CANCER",
		CASE WHEN DR.DESCRICAO IS NULL THEN ''NAO_INFORMADO'' ELSE DR.DESCRICAO END "DOENCA_DOS_RINS",
		PP.CANCER_OUTRO "CANCER_OUTRO",
		CASE PP.TEVE_INTERNACAO 
		WHEN TRUE THEN ''SIM''
		WHEN FALSE THEN ''NAO'' ELSE ''NAO_INFORMADO'' END "TEVE_INTERNACAO",
		PP.TEVE_INTERNACAO_MOTIVO "MOTIVO_DA_INTERNACAO",
		CASE PP.TRATAMENTO_MENTAL
		WHEN TRUE THEN ''SIM'' 
		WHEN FALSE THEN ''NAO'' ELSE ''NAO_INFORMADO'' END "FEZ_OU_FAZ_TRATAMENTO_COM_PSIQUIATRA",
		CASE PP.DOMICILIADO
		WHEN TRUE THEN ''SIM'' 
		WHEN FALSE THEN ''NAO'' ELSE ''NAO_INFORMADO'' END "ESTA_DOMICILIADO",
		CASE PP.DOMICILIADO_CUIDADOR
		WHEN TRUE THEN ''SIM'' 
		WHEN FALSE THEN ''NAO'' ELSE ''NAO_INFORMADO'' END "DOMICILIADO_TEM_CUIDADOR",
		PP.PLANTAS_MEDICINAIS "USA_PLANTAS_MEDICINAIS",
		CASE PP.PRATICAS_INTEGRATIVAS
		WHEN TRUE THEN ''SIM'' 
		WHEN FALSE THEN ''NAO'' ELSE ''NAO_INFORMADO'' END "USA_OUTRAS_PRATICAS_INTEGRATIVAS",
		PP.CONDICAO_SAUDE_1 "OUTRAS_CONDICOES_SAUDE_1",
		PP.CONDICAO_SAUDE_2 "OUTRAS_CONDICOES_SAUDE_2",
		PP.CONDICAO_SAUDE_3 "OUTRAS_CONDICOES_SAUDE_3"
	FROM SIABFACIL.PESSOA PP
	INNER JOIN SIABFACIL.FAMILIA FA ON FA.ID = PP.FAMILIA_ID
	INNER JOIN SIABFACIL.POSICAO_FAMILIAR PF ON PF.ID = PP.POSICAO_FAMILIAR_ID
	LEFT JOIN SIABFACIL.NACIONALIDADE NA ON NA.ID = PP.NACIONALIDADE_ID
	LEFT JOIN SIABFACIL.ESTADO_CIVIL EC ON PP.ESTADO_CIVIL_ID = EC.ID
	LEFT JOIN SIABFACIL.ESCOLARIDADE ES ON PP.ESCOLARIDADE_ID = ES.ID
	LEFT JOIN SIABFACIL.PLANO_DE_SAUDE PS ON PS.ID = PP.PLANO_DE_SAUDE_ID 
	LEFT JOIN SIABFACIL.SITUACAO_TRABALHO TR ON PP.SITUACAO_TRABALHO_ID = TR.ID
	LEFT JOIN SIABFACIL.RESPONSAVEL_CRIANCA RC ON PP.RESPONSAVEL_CRIANCA_ID = RC.ID
	LEFT JOIN SIABFACIL.PESSOA_DOENCA_CARDIACA DCA ON PP.ID = DCA.PESSOA_ID
	LEFT JOIN SIABFACIL.DOENCA_CARDIACA DC ON DCA.DOENCA_CARDIACA_ID = DC.ID
	LEFT JOIN SIABFACIL.PESSOA_DOENCA_RESPIRATORIA DRE ON PP.ID = DRE.PESSOA_ID
	LEFT JOIN SIABFACIL.DOENCA_RESPIRATORIA RE ON DRE.DOENCA_RESPIRATORIA_ID = RE.ID
	LEFT JOIN SIABFACIL.PESSOA_DOENCA_RINS PDR ON PP.ID = PDR.PESSOA_ID
	LEFT JOIN SIABFACIL.DOENCA_RINS DR ON PDR.DOENCA_RINS_ID = DR.ID
	LEFT JOIN SIABFACIL.TIPO_CANCER TC ON CAST(PP.CANCER AS INTEGER) = CAST(TC.ID AS INTEGER)
	LEFT JOIN SIABFACIL.ORIENTACAO_SEXUAL OS ON PP.ORIENTACAO_SEXUAL_ID = OS.ID
	LEFT JOIN SIABFACIL.PESSOA_GRUPO_DE_PESSOAS PGP ON  PP.ID = PGP.PESSOA_ID
	LEFT JOIN SIABFACIL.GRUPO_DE_PESSOAS GP ON PGP.GRUPO_DE_PESSOAS_ID = GP.ID
	LEFT JOIN SIABFACIL.SITUACAO_TRABALHO ST ON ST.ID = PP.SITUACAO_TRABALHO_ID
	LEFT JOIN SIABFACIL.OCUPACAO OC ON OC.ID = PP.OCUPACAO_ID
	LEFT JOIN CNES.LFCES018 A ON A.PROF_ID = FA.PROF_ID
	LEFT JOIN CNES.LFCES037 B ON B.COD_AREA = FA.COD_AREA
	LEFT JOIN CNES.NFCES038 C ON C.CD_RACA = PP.CD_RACA
	LEFT JOIN CNES.NFCES005 D ON FA.COD_MUN = D.COD_MUN
	LEFT JOIN CNES.NFCES036 E ON PP.PAIS_NASCIMENTO_ID = E.CD_PAIS
	WHERE PP.FAMILIA_ID IS NOT NULL
	AND PP.DATA_DESATIVACAO IS NULL
	AND B.CO_EQUIPE IS NOT NULL
	GROUP BY PP.ID, A.COD_CNS, B.CO_EQUIPE, D.COD_MUN, PP.CNS, PP.NOME, PP.TELEFONE, NA.DESCRICAO, PP.DATA_NASCIMENTO, PP.CPF, PP.DNV, PP.CNS, PP.SEXO, 
		 PF.DESCRICAO, C.DS_RACA, PF.DESCRICAO, ES.DESCRICAO, PS.NOME, ST.ID, B.NM_REFERENCIA, FA.COD_AREA, FA.MICROAREA, A.NOME_PROF, 
		 PP.DATA_ATIVACAO, FA.COD_AREA, FA.MICROAREA, FA.NUMERO, PP.APELIDO, PP.NIS, PP.NOME_DA_MAE, PP.MAE_DESCONHECIDA, NA.ID, E.DS_PAIS, 
		 PP.TELEFONE_2, PP.TELEFONE_3, PP.EMAIL, EC.DESCRICAO, ES.ID, TR.ID, RC.DESCRICAO, PP.FREQUENTA_BENZEDEIRA, PP.GRUPO_COMUNITARIO, 
		 PP.POVO_COMUNIDADE_TRADICIONAL, OS.DESCRICAO, GP.DESCRICAO, OC.DESCRICAO, PP.FREQUENTA_ESCOLA, PP.DEF_FISICA, PP.DEF_MENTAL, PP.DEF_VISUAL,
		 PP.DEF_AUDITIVA, GP.ID, PP.AVC_DERRAME, PP.INFARTO, RE.DESCRICAO, DC.DESCRICAO, DR.DESCRICAO, PP.TEM_TEVE_CANCER, PP.CANCER_OUTRO, 
		 PP.MATERNIDADE_REFERENCIA, TC.DESCRICAO, PP.TEVE_INTERNACAO, PP.TEVE_INTERNACAO_MOTIVO, PP.TRATAMENTO_MENTAL, PP.PLANTAS_MEDICINAIS,
		 PP.DOMICILIADO, PP.DOMICILIADO_CUIDADOR, PP.PRATICAS_INTEGRATIVAS, PP.CONDICAO_SAUDE_1, PP.CONDICAO_SAUDE_2, PP.CONDICAO_SAUDE_3
	')
)
go


SELECT B.IDPEP CODPAC, A.* FROM siabfacil.vw_ficha_deficiente A INNER JOIN INDICADORES.vw_pep_siab B ON A.idsiab = B.IDSIAB
SELECT B.IDPEP CODPAC, A.* FROM siabfacil.vw_ficha_b_tuberculose A INNER JOIN INDICADORES.vw_pep_siab B ON A.idsiab = B.IDSIAB
SELECT B.IDPEP CODPAC, A.* FROM siabfacil.vw_ficha_b_hipertenso A INNER JOIN INDICADORES.vw_pep_siab B ON A.idsiab = B.IDSIAB
SELECT B.IDPEP CODPAC, A.* FROM siabfacil.vw_ficha_b_hanseniase A INNER JOIN INDICADORES.vw_pep_siab B ON A.idsiab = B.IDSIAB
SELECT B.IDPEP CODPAC, A.* FROM siabfacil.vw_ficha_b_diabetico A INNER JOIN INDICADORES.vw_pep_siab B ON A.idsiab = B.IDSIAB
SELECT B.IDPEP CODPAC, A.* FROM siabfacil.vw_ficha_c_crianca A INNER JOIN INDICADORES.vw_pep_siab B ON A.idsiab = B.IDSIAB
SELECT B.IDPEP CODPAC, A.* FROM siabfacil.vw_ficha_gestante A INNER JOIN INDICADORES.vw_pep_siab B ON A.idsiab = B.IDSIAB
SELECT B.IDPEP CODPAC, A.* FROM siabfacil.vw_ficha_A_individual A INNER JOIN INDICADORES.vw_pep_siab B ON A.idsiab = B.IDSIAB
