USE RECEPCAO;
SET DATEFORMAT DMY
SELECT * FROM (
SELECT  DISTINCT A.NOME, A.NOMEEQUIPE, A.IDADE, A.MAE, A.PRONTUARIO, A.CNS, CONVERT (VARCHAR (20), B.DATA, 103) DataResultado, convert(varchar(max),B.RESULTADO) resultado, convert(varchar(max),B.observacao) observacao
FROM INDICADORES.VW_PEP_SIAB A
INNER JOIN EXAMES.MAMOGRAFIA B ON A.IDPEP = B.CODPAC
WHERE RESULTADO LIKE '%BIRADS 4%'
OR RESULTADO LIKE '%BIRADS 5%'
OR RESULTADO LIKE '%BIRADS 6%'
OR RESULTADO LIKE '%CATEGORIA 4%'
OR RESULTADO LIKE '%CATEGORIA 5%'
OR RESULTADO LIKE '%CATEGORIA 6%'
)QRY










