SELECT NOME, CPF,  CONVERT(VARCHAR(10), DTNASC, 103)DataNascimento, RUA + ',' + NUM Endereco, BAIRRO, CEP, TEL, TELCEL 
FROM PACIENTES
WHERE CODIGO NOT IN (SELECT IDPEP FROM INDICADORES.VW_PEP_SIAB A 
INNER JOIN PACIENTES B ON A.IDPEP = B.CODIGO)

