USE integracao
GO
DROP USER HMSC
GO
CREATE USER HMSC FROM LOGIN HMSC
GO
GRANT SELECT, UPDATE, DELETE, INSERT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE SCHEMA, ALTER, EXECUTE,CONNECT  TO HMSC
USE cadastro
GO
DROP USER HMSC
GO
CREATE USER HMSC FROM LOGIN HMSC
GO
GRANT SELECT, UPDATE, DELETE, INSERT, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE, CREATE FUNCTION, CREATE SCHEMA, ALTER, EXECUTE,CONNECT  TO HMSC