SET DATEFORMAT DMY
SELECT DISTINCT * FROM (
SELECT DISTINCT C.NOME AS NOME_DO_PACIENTE, C.NOMEEQUIPE AS NOME_DA_EQUIPE, C.SEXO, CONVERT (VARCHAR(10), 
DATA_NASCIMENTO,103) AS DATA_NASCIMENTO, C.MAE, D.CID10, D.DESCR,
(SELECT TOP 1 CONVERT (VARCHAR(10), dtatende,103 )  FROM pepmovimentos x where x.codpac=c.idpep order by codigo desc) AS DATA_ULTIMO_ATENDIMENTO, c.prontuario
FROM INDICADORES.VW_PEP_SIAB C
INNER JOIN PEPMOVIMENTOS A ON C.IDPEP = A.CODPAC
INNER JOIN PepMovimentos_CID B ON A.CODIGO = B.id_PepMovimentos
INNER JOIN CID D ON B.id_cid = D.ID
WHERE D.ID in(2407
,2418
,2429
,2440
,2451
,2462
,2473
,2484
,2495
,2506)
) AS TEMP
ORDER BY NOME_DA_EQUIPE

