/*Variáveis*/
--DECLARAR AS VARIÁVEIS
USE RECEPCAO
DECLARE @TESTE_TEXTO VARCHAR (200),
        @TESTE_NUM INT,
		@TESTE_DATA DATE,
		@TESTE_GRANA MONEY  

--INSERIR VALOR NA VARIÁVEL COM SET
SET @TESTE_TEXTO = 'DANILO'

-- CONSULTAR VALOR DA VARIÁVEL
SELECT @TESTE_TEXTO as texto

--INSERIR VALOR NA VARIÁVEL COM SELECT
USE RECEPCAO
DECLARE @TESTE_NUMERO INT
SELECT @TESTE_NUMERO = FICHA
FROM PEPMOVIMENTOS
SELECT  @TESTE_NUMERO AS CODIGO

